### ISSUE TITLE
"no other error listed"

### ISSUE THREAD

**Issue by mark-i-m** [alexcrichton/ssh2-rs#101]
Hi, I'm trying to debug an error I'm getting with [spurs](https://github.com/mark-i-m/spurs). It uses `ssh2` internally for SSH stuff.

Some long-running commands (multiple hours) get an error -1 "no other error listed", which I think can only come from ssh2. However, it seems that ssh2 only generates this error when `known_hosts` or `agent` is called, and I never call either of those. Do you have any ideas where I can start debugging?

Unfortunately, my code makes a ton of calls to do SSH things and I have not been able to produce a minimal reproduction yet, so narrowing down where the error is coming from is proving hard.

I realize that's not much to work with, but any pointers would be appreciated!

**Comment by alexcrichton** [comment]
Hm this may be a mishandled error code or something like that in the bindings library here, but it may also be a bug in libssh2 itself where an error is returned but extended error information isn't configured (or is clobbered later). Unfortunately I wouldn't know where to start looking myself :(

**Comment by mark-i-m** [comment]
Ok, thanks. I have added some better logging to my crate, and will check back in if I learn anything new...

**Comment by mark-i-m** [comment]
Ok, so I have started seeing this error again and this time, I have a bit of logging info. Here is the situation:

The `spurs` crate has a [`reconnect`](https://docs.rs/spurs/0.3.0/spurs/ssh/trait.Execute.html#tymethod.reconnect) method, which allows the user to reconnect a session. The use-case for this is for users to be able to run `sudo reboot` to reboot a remote machine. I have started getting this error message consistently after executing one command after rebooting.

- User executes `sudo reboot` remotely
- User calls `shell.reconnect()`
- `SshShell::reconnect` does the following:
    - Sits in a loop attempting to create a new `TcpStream`, with a timeout of 5 seconds and sleeping 5 seconds between attempts.
    - Once the `TcpStream` is established, a new SSH `Session` is created.
    - The SSH handshake is performed
    - The SSH authentication is performed using a public key file
- User executes `whoami` remotely to test the connection. This creates a new channel, executes the command remotely in a PTY, receives and prints the output of stdout and stderr, and returns an exit code of 0.
- The user then attempts to execute another command, but libssh2 is unable to create a channel, failing with "no other error listed".

**Comment by mark-i-m** [comment]
Just leaving some debugging notes for myself...

Here is my current guess. I need to do a bit more debugging to confirm or deny:

https://github.com/alexcrichton/ssh2-rs/blob/844b80094da0eb66aca7b3ff5f51c9f3ac3b5806/src/session.rs#L515-L535

The `SessionBinding::from_raw_opt` returns the "no other errors listed" when it receives a `null` value from libssh2 and the `libssh2_session_last_error` function also returns no error.

In this case, it looks like the following code is being triggered:

https://github.com/libssh2/libssh2/blob/1b3cbaff518f32e5b70650d4b7b52361b1410d37/src/channel.c#L355-L363

Specifically, it looks like the session passed to libssh2 is `null`. It looks like all the other errors set the error code before returning.

**Comment by mark-i-m** [comment]
Some more debugging:

This is the actual error case we are triggering in `libssh2`: https://github.com/libssh2/libssh2/blob/1b3cbaff518f32e5b70650d4b7b52361b1410d37/src/channel.c#L239

In this case, `rc == LIBSSH2_ERROR_SOCKET_RECV`, but the error code is never set. I have opened https://github.com/libssh2/libssh2/pull/381 to mildly improve this.

I still don't fully understand why this error happens _after_ we have already connected and executed a command. My guess is that is a different bug in libssh2, but I'm not sure.

**Comment by mark-i-m** [comment]
Ah, silly me :man_facepalming: 

I had two ssh sessions running. When I reboot the machine, I reconnect one but forget to reconnect the other :confounded: 

Thus, ends the mystery...
