### ISSUE TITLE
elliptic curve private keys don't work

### ISSUE THREAD

**Issue by Trolldemorted** [alexcrichton/ssh2-rs#105]
I am generating my keys with `ssh-keygen -t rsa/ed25519 -m pem` in a debian docker container (debian:stretch-slim with libssl-dev andopenssh-client). I am fairly certain I deployed the public keys correctly.

This works:
```rust
sess.userauth_pubkey_file(&destination.userauth_agent, Some(Path::new("./data/id_rsa.pub")), Path::new("./data/id_rsa"), None)?;
```

This doesn't:
```rust
sess.userauth_pubkey_file(&destination.userauth_agent, Some(Path::new("./data/id_ed25519.pub")), Path::new("./data/id_ed25519"), None)?;
```
>Err(Ssh2Error(Error { code: -19, msg: "Callback returned error" }))

Note: Omitting the pubkey for the ed25519 variant does not work either.

**Comment by alexcrichton** [comment]
Thanks for the report! This crate, however, is just bindings to libssh2, and bugs/questions about usage should likely go upstream to libssh2
