### ISSUE TITLE
Panic during handshake

### ISSUE THREAD

**Issue by kariae** [alexcrichton/ssh2-rs#106]
First of all thanks for the crate, well done ;)

I'm trying to transfer some file using SFTP, and I keep getting a panic during the handshake: `Unable to exchange encryption keys`

I'm on OSX, I updated openssl, but still having the same issue, any help please?

**Comment by alexcrichton** [comment]
Sorry I just maintain the bindings for this crate, and I'd recommend asking a question at the upstream libssh2 library itself
