### ISSUE TITLE
For scp_recv, read_to_end never return.

### ISSUE THREAD

**Issue by xiaoniu-578fa6bff964d005** [alexcrichton/ssh2-rs#107]
Using `read_to_end` will cause the block.
Looping `read(&mut [u8])` shows that `read` never return `Err(e)` or `Ok(0)`, and block at the next request after transfer finished.

My environment:
stable-x86_64-pc-windows-msvc.
rustc 1.32.0 (9fda7c223 2019-01-16)
libssh2-sys 0.2.11

**Comment by valerius21** [comment]
Error remains since commit `8e588457103bdb8a435a8bb29c8a04f49e912177`

**Comment by xiaoniu-578fa6bff964d005** [comment]
Possibly related to #109, in which time is misinterpreted as file size.

**Comment by valerius21** [comment]
Couldn't get it working with any version of this crate.

**Comment by JoyceBabu** [comment]
@xiaoniu-578fa6bff964d005 Where you able to work around this?

**Comment by xiaoniu-578fa6bff964d005** [comment]
Use Python LOL!

**Comment by wez** [comment]
Closing this as a duplicate of #109
