### ISSUE TITLE
compiling failed in installation of mdbook-epub

### ISSUE THREAD

**Issue by lidanger** [alexcrichton/ssh2-rs#108]
output log in the console window:
error: failed to run custom build command for libssh2-sys v0.2.6
process didn't exit successfully: E:\Test\mdbook-epub-0.1.0\target\release\build\libssh2-sys-054ac8fbde399b72\build-script-build (exit code: 101)
--- stdout
running: "cmake" "C:\Users\ljd\.cargo\registry\src\github.com-1ecc6299db9ec823\libssh2-sys-0.2.6\libssh2" "-G" "Visual Studio 15 2017 Win64" "-DCRYPTO_BACKEND=WinCNG" "-DZLIB_INCLUDE_DIR=E:\Test\mdbook-epub-0.1.0\target\release\build\libz-sys-f137a425f38f13de\out/include" "-DBUILD_SHARED_LIBS=OFF" "-DENABLE_ZLIB_COMPRESSION=ON" "-DCMAKE_INSTALL_LIBDIR=lib" "-DBUILD_EXAMPLES=OFF" "-DBUILD_TESTING=OFF" "-DCMAKE_INSTALL_PREFIX=E:\Test\mdbook-epub-0.1.0\target\release\build\libssh2-sys-1872c162ac6e8a5f\out" "-DCMAKE_C_FLAGS= /nologo /MD" "-DCMAKE_C_FLAGS_RELEASE= /nologo /MD" "-DCMAKE_CXX_FLAGS= /nologo /MD" "-DCMAKE_CXX_FLAGS_RELEASE= /nologo /MD" "-DCMAKE_BUILD_TYPE=Release"
-- The C compiler identification is unknown
-- Configuring incomplete, errors occurred!
See also "E:/Test/mdbook-epub-0.1.0/target/release/build/libssh2-sys-1872c162ac6e8a5f/out/build/CMakeFiles/CMakeOutput.log".
See also "E:/Test/mdbook-epub-0.1.0/target/release/build/libssh2-sys-1872c162ac6e8a5f/out/build/CMakeFiles/CMakeError.log".
--- stderr
fatal: Not a git repository (or any of the parent directories): .git
CMake Error at CMakeLists.txt:40 (project):
No CMAKE_C_COMPILER could be found.
thread 'main' panicked at '
command did not execute successfully, got: exit code: 1
build script failed, must exit now', C:\Users\ljd.cargo\registry\src\github.com-1ecc6299db9ec823\cmake-0.1.29\src\lib.rs:632:5
note: Run with RUST_BACKTRACE=1 environment variable to display a backtrace.
warning: build failed, waiting for other jobs to finish...
error: failed to compile mdbook-epub v0.1.0 (E:\Test\mdbook-epub-0.1.0), intermediate artifacts can be found at E:\Test\mdbook-epub-0.1.0\target
Caused by:
build failed

CMakeError.log:
Compiling the C compiler identification source file "CMakeCCompilerId.c" failed.
Compiler:
Build flags: ;/nologo;/MD
Id flags:
The output was:
1
用于 .NET Framework 的 Microsoft (R) 生成引擎版本 15.9.21+g9802d43bc3
版权所有(C) Microsoft Corporation。保留所有权利。
生成启动时间为 2019-03-03 12:00:42。
节点 1 上的项目“E:\Test\mdbook-epub-0.1.0\target\release\build\libssh2-sys-1872c162ac6e8a5f\out\build\CMakeFiles\3.13.4\CompilerIdC\CompilerIdC.vcxproj”(默认目标)。
PrepareForBuild:
正在创建目录“Debug\”。
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.CppBuild.targets(402,5): warning MSB8038: 已启用 Spectre 缓解，但找不到 Spectre 缓解库。验证 Visual Studio 工作负荷包括 Spectre 缓解库。有关详细信息，请参阅 https://aka.ms/Ofhn4c。 [E:\Test\mdbook-epub-0.1.0\target\release\build\libssh2-sys-1872c162ac6e8a5f\out\build\CMakeFiles\3.13.4\CompilerIdC\CompilerIdC.vcxproj]
正在创建目录“Debug\CompilerIdC.tlog\”。
InitializeBuildStatus:
正在创建“Debug\CompilerIdC.tlog\unsuccessfulbuild”，因为已指定“AlwaysCreate”。
ClCompile:
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\bin\HostX86\x64\CL.exe /c /nologo /W0 /WX- /diagnostics:classic /Od /D _MBCS /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Qspectre /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"Debug\" /Fd"Debug\vc141.pdb" /Gd /TC /FC /errorReport:queue CMakeCCompilerId.c
CMakeCCompilerId.c
Link:
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\bin\HostX86\x64\link.exe /ERRORREPORT:QUEUE /OUT:".\CompilerIdC.exe" /INCREMENTAL:NO /NOLOGO kernel32.lib user32.lib gdi32.lib winspool.lib comdlg32.lib advapi32.lib shell32.lib ole32.lib oleaut32.lib uuid.lib odbc32.lib odbccp32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /PDB:".\CompilerIdC.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:".\CompilerIdC.lib" /MACHINE:X64 Debug\CMakeCCompilerId.obj
LINK : fatal error LNK1104: 无法打开文件“MSVCRTD.lib” [E:\Test\mdbook-epub-0.1.0\target\release\build\libssh2-sys-1872c162ac6e8a5f\out\build\CMakeFiles\3.13.4\CompilerIdC\CompilerIdC.vcxproj]
已完成生成项目“E:\Test\mdbook-epub-0.1.0\target\release\build\libssh2-sys-1872c162ac6e8a5f\out\build\CMakeFiles\3.13.4\CompilerIdC\CompilerIdC.vcxproj”(默认目标)的操作 - 失败。
生成失败。
“E:\Test\mdbook-epub-0.1.0\target\release\build\libssh2-sys-1872c162ac6e8a5f\out\build\CMakeFiles\3.13.4\CompilerIdC\CompilerIdC.vcxproj”(默认目标) (1) ->
(PrepareForBuild 目标) ->
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.CppBuild.targets(402,5): warning MSB8038: 已启用 Spectre 缓解，但找不到 Spectre 缓解库。验证 Visual Studio 工作负荷包括 Spectre 缓解库。有关详细信息，请参阅 https://aka.ms/Ofhn4c。 [E:\Test\mdbook-epub-0.1.0\target\release\build\libssh2-sys-1872c162ac6e8a5f\out\build\CMakeFiles\3.13.4\CompilerIdC\CompilerIdC.vcxproj]
“E:\Test\mdbook-epub-0.1.0\target\release\build\libssh2-sys-1872c162ac6e8a5f\out\build\CMakeFiles\3.13.4\CompilerIdC\CompilerIdC.vcxproj”(默认目标) (1) ->
(Link 目标) ->
LINK : fatal error LNK1104: 无法打开文件“MSVCRTD.lib” [E:\Test\mdbook-epub-0.1.0\target\release\build\libssh2-sys-1872c162ac6e8a5f\out\build\CMakeFiles\3.13.4\CompilerIdC\CompilerIdC.vcxproj]
1 个警告
1 个错误
已用时间 00:00:01.36

environment:
rustc 1.33.0 (2aa4c46cf 2019-02-28)
Windows 10 Professional 17763
Visual Studio 2017 Community 15.9.7
CMake 3.13.4

[mdbook-epub repo](https://github.com/Michael-F-Bryan/mdbook-epub)

**Comment by xiaoniu-578fa6bff964d005** [comment]
Did you install `vcpkg`? 
I found similar error like `fatal: Not a git repository (or any of the parent directories): .git` and after installed vcpkg, the error vanished.

**Comment by lidanger** [comment]
I tried to intall vcpkg just now. There is a waring message too:
MSB8038:已启用Spectre缓解，但找不到Spectre缓解库。验证Visual Studio工作负荷包括Spectre缓解库。
LNK1104:无法打开文件"msvcprtd.lib".

I searched the keyword "Spectre缓解", then found a solution, refer to [Spectre小计](https://www.cnblogs.com/qiyueliuguang/p/10370292.html)

It seems the component VC++ 2017 version 15.9 v14.16 Libs for Spectre (x86 and x64) is not installed. I installed it, yes ,it's ok now.

Thank you, @xiaoniu-578fa6bff964d005
