### ISSUE TITLE
SCP receive file size error on windows.

### ISSUE THREAD

**Issue by xiaoniu-578fa6bff964d005** [alexcrichton/ssh2-rs#109]
When I download a file of 4 bytes size, `ScpFileStat.size()` shows 1552549416, which is actually current time.

Some debug indicate that this issue is caused by different layout between `libc::windows::stat` and `stat`.

Here are the interpretations of same memory block for `libc::windows::stat`:
![图片](https://user-images.githubusercontent.com/32661032/54342908-9321da80-4678-11e9-9f83-bde57d37d0cf.png)
and for `stat`:
![图片](https://user-images.githubusercontent.com/32661032/54342931-9ae17f00-4678-11e9-82c6-05c699f1cd54.png)

The `libssh2_struct_stat` have same layout with `libc::windows::stat`, however the input argument of `libssh2_scp_recv` in `libssh2-sys` is of type `stat`, [ref](https://github.com/alexcrichton/libssh2/blob/master/src/scp.c#L770).

Here is the memory layout of `libc::windows::stat` on my computer:
type: `libc::windows::stat`: 56 bytes, alignment: 8 bytes
field `.st_dev`: 4 bytes
field `.st_ino`: 2 bytes
field `.st_mode`: 2 bytes
field `.st_nlink`: 2 bytes
field `.st_uid`: 2 bytes
field `.st_gid`: 2 bytes
padding: 2 bytes
field `.st_rdev`: 4 bytes, alignment: 4 bytes
padding: 4 bytes
field `.st_size`: 8 bytes, alignment: 8 bytes
field `.st_atime`: 8 bytes
field `.st_mtime`: 8 bytes
field `.st_ctime`: 8 bytes
Size of `stat`: 48 bytes.

My environment:
rustc 1.32.0 (9fda7c223 2019-01-16)
stable-x86_64-pc-windows-msvc and stable-x86_64-pc-windows-gnu(with MinGW-W64)

cargo.lock:
libssh2-sys 0.2.11
libc 0.2.50

**Comment by xiaoniu-578fa6bff964d005** [comment]
However, for `stat`, the field `st_size` just fall into the `padding: 4 bytes` range.

**Comment by xiaoniu-578fa6bff964d005** [comment]
It confuse me alot why `stat` and `libssh2_struct_stat` is of different size.
According to [this line](https://github.com/libssh2/libssh2/blob/master/include/libssh2.h#L224) they should be same.

**Comment by alexcrichton** [comment]
This may be a case where `stat` vs `stat64` or something like that is causing problems, and this is likely a bug in the `libssh2-sys` crate itself.

If you can checkout the repository and run `cargo run` in `systest` it should alert any differences between the two

**Comment by valerius21** [comment]
Unfortunately, it does not.
```
warning: cl : Command line warning D9025 : overriding '/W4' with '/W3'
warning: use of deprecated item 'std::sync::atomic::ATOMIC_BOOL_INIT': the `new` function is now preferred
 --> C:\Users\Valerius\Desktop\_ssh\ssh2-rs\target\debug\build\systest-07db2a0d3075e19a\out/all.rs:4:49
  |
4 |             use std::sync::atomic::{AtomicBool, ATOMIC_BOOL_INIT, Ordering};
  |                                                 ^^^^^^^^^^^^^^^^
  |
  = note: #[warn(deprecated)] on by default

warning: use of deprecated item 'std::sync::atomic::ATOMIC_USIZE_INIT': the `new` function is now preferred
 --> C:\Users\Valerius\Desktop\_ssh\ssh2-rs\target\debug\build\systest-07db2a0d3075e19a\out/all.rs:5:50
  |
5 |             use std::sync::atomic::{AtomicUsize, ATOMIC_USIZE_INIT};
  |                                                  ^^^^^^^^^^^^^^^^^

warning: use of deprecated item 'std::sync::atomic::ATOMIC_BOOL_INIT': the `new` function is now preferred
  --> C:\Users\Valerius\Desktop\_ssh\ssh2-rs\target\debug\build\systest-07db2a0d3075e19a\out/all.rs:41:41
   |
41 |             static FAILED: AtomicBool = ATOMIC_BOOL_INIT;
   |                                         ^^^^^^^^^^^^^^^^
help: use of deprecated item 'std::sync::atomic::ATOMIC_BOOL_INIT': the `new` function is now preferred
   |
41 |             static FAILED: AtomicBool = AtomicBool::new(false);
   |                                         ^^^^^^^^^^^^^^^^^^^^^^

warning: use of deprecated item 'std::sync::atomic::ATOMIC_USIZE_INIT': the `new` function is now preferred
  --> C:\Users\Valerius\Desktop\_ssh\ssh2-rs\target\debug\build\systest-07db2a0d3075e19a\out/all.rs:42:42
   |
42 |             static NTESTS: AtomicUsize = ATOMIC_USIZE_INIT;
   |                                          ^^^^^^^^^^^^^^^^^
help: use of deprecated item 'std::sync::atomic::ATOMIC_USIZE_INIT': the `new` function is now preferred
   |
42 |             static NTESTS: AtomicUsize = AtomicUsize::new(0);
   |                                          ^^^^^^^^^^^^^^^^^^^

    Finished dev [unoptimized + debuginfo] target(s) in 1m 04s
     Running `C:\Users\Valerius\Desktop\_ssh\ssh2-rs\target\debug\systest.exe`
RUNNING ALL TESTS
PASSED 769 tests
```

**Comment by JoyceBabu** [comment]
I am also seeing the same issue.

**Comment by JoyceBabu** [comment]
On 64 bit build it is returning the timestamp. But on 32 bit build, it is returning an even bigger number.

For a file of size 40960 bytes, I am getting the following sizes depending on the target architecture. 

64 Bit - 1563919174
32 Bit - 6716986311686195062

**Comment by JoyceBabu** [comment]
I found the following comment in `libssh2.h`

```
/* libssh2_scp_recv is DEPRECATED, do not use! */
LIBSSH2_API LIBSSH2_CHANNEL *libssh2_scp_recv(LIBSSH2_SESSION *session,
                                              const char *path,
                                              struct stat *sb);
/* Use libssh2_scp_recv2 for large (> 2GB) file support on windows */
LIBSSH2_API LIBSSH2_CHANNEL *libssh2_scp_recv2(LIBSSH2_SESSION *session,
                                               const char *path,
                                               libssh2_struct_stat *sb);
```

So I tried updating `sess.scp_recv` to use `libssh2_scp_recv2` instead of the deprecated `libssh2_scp_recv`, and now it is working correctly on both Windows and macOS.
