### ISSUE TITLE
libssh2 does not use poll() on Ubuntu

### ISSUE THREAD

**Issue by susu** [alexcrichton/ssh2-rs#110]
Compiling on Ubuntu, it will not use poll(), but uses select(). However the original libssh2 library would use poll (probably other linux distributions are affected as well).

It is because in libssh2-sys crate's build.rs will not define the HAVE_POLL macro.

We hit the limit (1024) of select() (number of FDs), as we initiating more than 1024 ssh connections.

I'd like to put the logic into build.rs, however I'm not sure how to do it:
"if the system has poll(), then define HAVE_POLL"

**Comment by alexcrichton** [comment]
Oh dear, good point! Would you be interested in sending a PR for this? I think it'd be a pretty simple change to the build script

**Comment by susu** [comment]
Yeah, I'm on it. Not sure though how should I check an existence of a C function. Or is it enough to check the existence of poll.h in the system's include path?

**Comment by alexcrichton** [comment]
Ah it's fine to not worry much about that, I think that's to support systems from the 80s or something like that, everything has poll.h today so it's fine to unconditionally define it until we hear otherwise.

**Comment by susu** [comment]
Checking the libssh2's CMakeLists.txt: it explicitly disables poll() for MacOSX.

https://github.com/alexcrichton/libssh2/blob/6d70b26ab602d112707890608455caf29ec9a358/src/CMakeLists.txt#L320

**Comment by susu** [comment]
Came up with this: https://github.com/susu/ssh2-rs/commit/3e7197879ccfe6584a6bb461012b1b0a2515a8d6

I will test whether it solves our issue and then open a merge request.

**Comment by alexcrichton** [comment]
Sounds reasonable to me! That may need to also be disabled for Windows, but otherwise I think is good to make progress.

Honestly IIRC disabling `poll` on OSX was for some really obscure issue long ago fixed, so I think it'd be fine to enable it on OSX too

**Comment by susu** [comment]
Tested on Ubuntu 18.04 and worked well, I could open more than 1024 connections. I'll send the PR soon.
