### ISSUE TITLE
Cut new release

### ISSUE THREAD

**Issue by jonhoo** [alexcrichton/ssh2-rs#112]
There are a few updates and fixes that have been on `master` for a while (like https://github.com/alexcrichton/ssh2-rs/pull/97) but that aren't in 0.3.3. @alexcrichton would you consider doing a 0.4 release?

**Comment by alexcrichton** [comment]
I'm unfortunately not able to maintain the `ssh2` crate any more (especially with the recent influx of PRs). I'd be interested though in [finding a new home](https://github.com/alexcrichton/ssh2-rs/pull/113#issuecomment-514650379) for the crate!

**Comment by crisidev** [comment]
@wez Do you have an idea of when 0.4 will be released?

**Comment by wez** [comment]
I need to get some of @alexcrichton's time to release the underlying sys crate, including some fixes for Windows 10.  I'm hoping to run into him at RustConf this week, so possibly by this weekend.

**Comment by crisidev** [comment]
Oh! I Just landed in Portland for the same reason. We will see each other at the conf..

**Comment by wez** [comment]
I'm arriving tomorrow afternoon; will see you there!

**Comment by wez** [comment]
this is what I plan to use in the next release of both the `-sys` and the higher level crates:

https://github.com/alexcrichton/ssh2-rs/pull/127

**Comment by wez** [comment]
I've (finally!) published ssh2 0.4.0 and libssh2-sys 0.2.12 to crates.io!

**Comment by crisidev** [comment]
\0/ Thanks a ton for the effort man. Really appreciated!
