### ISSUE TITLE
minimum rustc version?

### ISSUE THREAD

**Issue by wez** [alexcrichton/ssh2-rs#119]
`pkg-config` 0.3.15, which was recently updated, doesn't compile with rust 1.26 any longer, and 1.26 is currently explicitly tested on travis.

I can tactically fix that failure using this little diff:

```
$ git diff
diff --git a/libssh2-sys/Cargo.toml b/libssh2-sys/Cargo.toml
index dbc604a..f75e5c5 100644
--- a/libssh2-sys/Cargo.toml
+++ b/libssh2-sys/Cargo.toml
@@ -20,7 +20,7 @@ libc = "0.2"
 openssl-sys = "0.9.35"

 [build-dependencies]
-pkg-config = "0.3.11"
+pkg-config = "=0.3.11"
 cc = "1.0.25"

 [target.'cfg(target_env = "msvc")'.build-dependencies]
```

but it seems better to me to raise the minimum version requirement to something more recent.
Thoughts on what that should be?

**Comment by wez** [comment]
@alexcrichton here's an indirect `libssh2-sys` issue for your consideration; is there a minimum rustc version we need to support?

**Comment by alexcrichton** [comment]
I think it's fine to not have a minimum rustc version effectively. I find a good rule of thumb is currenty rustc stable minus one or two, but especially for dealing with transitive dependencies there's nothing really we can do.
