### ISSUE TITLE
Cross-Compile for windows on linux fails

### ISSUE THREAD

**Issue by nathansamson** [alexcrichton/ssh2-rs#124]
I am probably missing something in my cross compile environment, but I am wonderign what...
If someone could point me to the right solution?

Do I need to compile zlib manually?

`error: failed to run custom build command for `libssh2-sys v0.2.11`

Caused by:
  process didn't exit successfully: `/builds/beeple/awsctl/target/release/build/libssh2-sys-66ac48215c76f5cb/build-script-build` (exit code: 1)
--- stdout
cargo:include=/builds/beeple/awsctl/target/x86_64-pc-windows-gnu/release/build/libssh2-sys-ffd6574506149f09/out/include
cargo:root=/builds/beeple/awsctl/target/x86_64-pc-windows-gnu/release/build/libssh2-sys-ffd6574506149f09/out
TARGET = Some("x86_64-pc-windows-gnu")
OPT_LEVEL = Some("3")
HOST = Some("x86_64-unknown-linux-gnu")
CC_x86_64-pc-windows-gnu = None
CC_x86_64_pc_windows_gnu = None
TARGET_CC = None
CC = None
CROSS_COMPILE = None
CFLAGS_x86_64-pc-windows-gnu = None
CFLAGS_x86_64_pc_windows_gnu = None
TARGET_CFLAGS = None
CFLAGS = None
CRATE_CC_NO_DEFAULTS = None
DEBUG = Some("false")
CARGO_CFG_TARGET_FEATURE = Some("fxsr,sse,sse2")
running: "x86_64-w64-mingw32-gcc" "-O3" "-ffunction-sections" "-fdata-sections" "-m64" "-I" "/builds/beeple/awsctl/target/x86_64-pc-windows-gnu/release/build/libssh2-sys-ffd6574506149f09/out/include" "-I" "libssh2/src" "-I" "libssh2/win32" "-DHAVE_LONGLONG" "-DLIBSSH2_WINCNG" "-DLIBSSH2_HAVE_ZLIB" "-o" "/builds/beeple/awsctl/target/x86_64-pc-windows-gnu/release/build/libssh2-sys-ffd6574506149f09/out/build/libssh2/src/agent.o" "-c" "libssh2/src/agent.c"
exit code: 0
running: "x86_64-w64-mingw32-gcc" "-O3" "-ffunction-sections" "-fdata-sections" "-m64" "-I" "/builds/beeple/awsctl/target/x86_64-pc-windows-gnu/release/build/libssh2-sys-ffd6574506149f09/out/include" "-I" "libssh2/src" "-I" "libssh2/win32" "-DHAVE_LONGLONG" "-DLIBSSH2_WINCNG" "-DLIBSSH2_HAVE_ZLIB" "-o" "/builds/beeple/awsctl/target/x86_64-pc-windows-gnu/release/build/libssh2-sys-ffd6574506149f09/out/build/libssh2/src/bcrypt_pbkdf.o" "-c" "libssh2/src/bcrypt_pbkdf.c"
exit code: 0
running: "x86_64-w64-mingw32-gcc" "-O3" "-ffunction-sections" "-fdata-sections" "-m64" "-I" "/builds/beeple/awsctl/target/x86_64-pc-windows-gnu/release/build/libssh2-sys-ffd6574506149f09/out/include" "-I" "libssh2/src" "-I" "libssh2/win32" "-DHAVE_LONGLONG" "-DLIBSSH2_WINCNG" "-DLIBSSH2_HAVE_ZLIB" "-o" "/builds/beeple/awsctl/target/x86_64-pc-windows-gnu/release/build/libssh2-sys-ffd6574506149f09/out/build/libssh2/src/blowfish.o" "-c" "libssh2/src/blowfish.c"
exit code: 0
running: "x86_64-w64-mingw32-gcc" "-O3" "-ffunction-sections" "-fdata-sections" "-m64" "-I" "/builds/beeple/awsctl/target/x86_64-pc-windows-gnu/release/build/libssh2-sys-ffd6574506149f09/out/include" "-I" "libssh2/src" "-I" "libssh2/win32" "-DHAVE_LONGLONG" "-DLIBSSH2_WINCNG" "-DLIBSSH2_HAVE_ZLIB" "-o" "/builds/beeple/awsctl/target/x86_64-pc-windows-gnu/release/build/libssh2-sys-ffd6574506149f09/out/build/libssh2/src/channel.o" "-c" "libssh2/src/channel.c"
exit code: 0
running: "x86_64-w64-mingw32-gcc" "-O3" "-ffunction-sections" "-fdata-sections" "-m64" "-I" "/builds/beeple/awsctl/target/x86_64-pc-windows-gnu/release/build/libssh2-sys-ffd6574506149f09/out/include" "-I" "libssh2/src" "-I" "libssh2/win32" "-DHAVE_LONGLONG" "-DLIBSSH2_WINCNG" "-DLIBSSH2_HAVE_ZLIB" "-o" "/builds/beeple/awsctl/target/x86_64-pc-windows-gnu/release/build/libssh2-sys-ffd6574506149f09/out/build/libssh2/src/comp.o" "-c" "libssh2/src/comp.c"
cargo:warning=libssh2/src/comp.c:41:11: fatal error: zlib.h: No such file or directory
cargo:warning= # include <zlib.h>
cargo:warning=           ^~~~~~~~
cargo:warning=compilation terminated.
exit code: 1

--- stderr
fatal: not a git repository (or any of the parent directories): .git

error occurred: Command "x86_64-w64-mingw32-gcc" "-O3" "-ffunction-sections" "-fdata-sections" "-m64" "-I" "/builds/beeple/awsctl/target/x86_64-pc-windows-gnu/release/build/libssh2-sys-ffd6574506149f09/out/include" "-I" "libssh2/src" "-I" "libssh2/win32" "-DHAVE_LONGLONG" "-DLIBSSH2_WINCNG" "-DLIBSSH2_HAVE_ZLIB" "-o" "/builds/beeple/awsctl/target/x86_64-pc-windows-gnu/release/build/libssh2-sys-ffd6574506149f09/out/build/libssh2/src/comp.o" "-c" "libssh2/src/comp.c" with args "x86_64-w64-mingw32-gcc" did not execute successfully (status code exit code: 1).`

**Comment by nathansamson** [comment]
Ok found the solution!

First I had to install `libz-mingw-w64-dev` (debian / ubuntu), then I also had to run with the `LIBZ_SYS_STATIC=1` env variable to prevent linking errors

**Comment by nathansamson** [comment]
Not sure if it is to be expected that dynamic linking does not compile, but including it static seems common (I would have expected it to be default then, but that is libz-sys's job so not for discussion here)

**Comment by wez** [comment]
Thanks for sharing your solution!

The logic in `libssh2-sys/build.rs` might need some refinements to make zlib detection more flexible, especially when cross compilation is involved.

I would generally recommend static linkage for most of these sorts of deps, so if you're happy with that, then I would leave dynamic linking for someone else that needs it :)
