### ISSUE TITLE
connecting to ssh-agent failed under windows openssh installation.

### ISSUE THREAD

**Issue by jianglibo** [alexcrichton/ssh2-rs#125]
make sure ssh-agent is running:
```
Status   Name               DisplayName
------   ----               -----------
Running  ssh-agent          OpenSSH Authentication Agent
```
make sure ssh-add is working.

I ran the code bellow it always return error: 'Error { code: -42, msg: "failed connecting agent" }', maybe is an issue of libssh2.

```rust
    #[test]
    fn t_main_agent_inspect() {
        // Almost all APIs require a `Session` to be available
        let sess = Session::new().unwrap();
        let mut agent = sess.agent().unwrap();

        // Connect the agent and request a list of identities
        agent.connect().unwrap();
        agent.list_identities().unwrap();

        for identity in agent.identities() {
            let identity = identity.unwrap(); // assume no I/O errors
            println!("{}", identity.comment());
            let pubkey = identity.blob();
            println!("{:?}", pubkey);
        }
    }
```

**Comment by wez** [comment]
Looking at the code in libssh2, it looks like it prefers to use the putty pageant, and then falls back to using the contents of `$SSH_AUTH_SOCK` if `PF_UNIX` is defined.  I'm not sure that `PF_UNIX` is defined consistently when building `libssh2` (probably not for the gnu toolchain, and it depends on your local compiler installation for MSVC), so the unix domain code is probably not even enabled on windows.  In addition, `SSH_AUTH_SOCK` doesn't appear to be set for me on Windows either... so I suspect that there is some amount of work needed to teach `libssh2` how to talk to the agent on windows, and then to make sure that we enable that code here in the rust bindings that bundle and build the library.

I would suggest opening an issue at https://github.com/libssh2/libssh2/issues/new/choose to see what the libssh2 folks think about making this work in libssh2, and then we can follow up from there.

**Comment by jianglibo** [comment]
Yes. Maybe only the ssh.exe come with ssh-agent.exe can understand this specialized ssh-agent service.

**Comment by wez** [comment]
(closing since this is something that needs to be addressed in the underlying libssh2 library)

**Comment by yodaldevoid** [comment]
I am attempting to add support for ssh-agent.exe in libssh2/libssh2#517, but the maintainers would like someone with Windows experience to take a look at the code before merging it. I don't know if any of the maintainers would be able to comment on that PR, but it would be appreciated.
