### ISSUE TITLE
session.scp_recv return wrong stat.

### ISSUE THREAD

**Issue by jianglibo** [alexcrichton/ssh2-rs#126]
The code bellow uses sftp to read a remote file it's ok.
```rust
    #[test]
    fn t_sftp_file() -> Result<(), failure::Error> {
        log_util::setup_logger(vec![""], vec![]).expect("log should init.");
        let (tcp, sess, dev_env) = develope_data::connect_to_ubuntu();
        info!("{:?}", tcp);
        let sftp = sess.sftp().expect("should got sfpt instance.");

        let mut file: ssh2::File =
            sftp.open(Path::new(&dev_env.servers.ubuntu18.test_dirs.aatxt))?;
        let mut buf = String::new();
        file.read_to_string(&mut buf)?;
        assert_eq!(buf, "hello\nworld\n");
        assert_eq!(buf.len(), 12);
        info!("{:?}", buf);
        Ok(())
    }
```
For the same file, use scp_recv,  it print out ```remote file size: 1565315783```, the file size is ~~always 1565315783~~ a very big value.. Did I missing some thing?
```rust
    #[test]
    fn t_scp_file() {
        log_util::setup_logger(vec![""], vec![]).expect("log should init.");
        let (tcp, sess, dev_env) = develope_data::connect_to_ubuntu();
        info!("{:?}", tcp);
        let (mut remote_file, stat) = sess
            .scp_recv(Path::new(&dev_env.servers.ubuntu18.test_dirs.aatxt))
            .unwrap();
        println!("remote file size: {}", stat.size());
        let mut contents = Vec::new();
        remote_file.read_to_end(&mut contents).unwrap();
        info!("{:?}", contents);
    }
```

**Comment by wez** [comment]
Sounds like https://github.com/alexcrichton/ssh2-rs/issues/109 which is fixed in master; can you confirm which version of the crate you are using?

**Comment by jianglibo** [comment]
I'm using the latest version. ```ssh2=0.3```. The server side is unbuntu18 in virtualbox environment, running ```OpenSSH_7.6p1 Ubuntu-4ubuntu0.3, OpenSSL 1.0.2n  7 Dec 2017```.

**Comment by wez** [comment]
Try with `ssh2 = { git = "https://github.com/alexcrichton/ssh2-rs" }` (or if you're on the latest windows 10, you may want `ssh2 = {git="https://github.com/wez/ssh2-rs", branch="win10dh"}` to pick up a fix for libssh2 on windows 10 (https://github.com/alexcrichton/ssh2-rs/issues/122).

**Comment by wez** [comment]
0.4.0 has just been published to crates.io
