### ISSUE TITLE
Sftp's readdir() might return wrong paths (windows)

### ISSUE THREAD

**Issue by gfriloux** [alexcrichton/ssh2-rs#129]
when requesting to list files of a path, ssh2-rs will add path delimiters using `Path::join`.
This means that it is OS dependent, and under windows, it will add a `\` char as path delimiter while path delimiters on SFTP is strictly specified as `/`.
So, listing `/var` will for example list a file named `/var\log` which is unusable (stat, readdir etc on it will fail), while listing `/var/` will be correct (but it will return `/var/log` that you can't use for `Sftp::readdir` or the bug will rise again).

As far as i know, only `/` is allowed as path delimiter, on SFTP:
https://tools.ietf.org/html/draft-ietf-secsh-filexfer-13:
```
   This protocol represents file names as strings.  File names are
   assumed to use the slash ('/') character as a directory separator.
```

To my understanding, using `Path::join` for `Sftp::readdir` is wrong.
A nasty workaround is to add at app level the delimiter as last char (this will silence the `Path::join` function), meaning that you cant directly list a directory, and access its content → you NEED to alter the filename to add a final `/` to any directory.
I noticed issue #99 that is supposed to solve the issue, but i don't get how it fixes anything:
- It modifies `utils::path2bytes` but this function isnt used by `Sftp::readdir`.
- Why anyone would choose to keep a function that adds a wrong char (and we know it), to fix it afterward?

For a quicker overlook, here is the "bad" code:
```rust
        loop {
            match dir.readdir() {
                Ok((filename, stat)) => {
                    if &*filename == Path::new(".") || &*filename == Path::new("..") {
                        continue;
                    }

                    ret.push((dirname.join(&filename), stat))
                }
                Err(ref e) if e.code() == raw::LIBSSH2_ERROR_FILE => break,
                Err(e) => return Err(e),
            }
        }
```

If i did not understand something correctly, i apologize for the noise, but please take the time to explain me why i am wrong.

**Comment by gfriloux** [comment]
I just saw that `utils::path2bytes` is called indirectly by `Sftp::readdir` here : https://github.com/alexcrichton/ssh2-rs/blob/master/src/sftp.rs#L128


But from my point of view, it is still wrong to do so.
Any App using ssh2-rs will handle wrong paths.

**Comment by gfriloux** [comment]
To be honest, i dont really understand why i am getting the `\` bug as `utils::path2bytes` seems te be called everywhere, and is supposed to work, but i do get it.

**Comment by gfriloux** [comment]
Ok, patch on `utils::path2bytes` hasn't been release yet as latest release on crates.io is `0.3.3` from may 2018.

**Comment by gfriloux** [comment]
Ok, so my biggest mistake was to thing that as it was fixed on december 2018, it was released (issue doesnt have any milestone or tag).

After looking at release dates, and commits, i have finally understand that this fix is for 0.4.0.
So i did build ssh2-rs from github master (nice changes with session.set_tcp_stream btw, i no more need lifetime parameters around session) and everything is working as i wanted to.

So i close my definitely useless issue as i was working with latest release, while it was already fixed for future release.

**Comment by wez** [comment]
Sorry for the confusion; it's been a bit of a battle to release master as 0.4.0; that effort is being tracked in https://github.com/alexcrichton/ssh2-rs/pull/127

**Comment by gfriloux** [comment]
No problem, this is things i should have checked myself =)

**Comment by piperun** [comment]
Has this Issue been fixed?
I'm getting the same problem but it's:
`path\\[found path from readdir()]`
And I'm using ssh2-rs v0.8

**Comment by wez** [comment]
@piperun my understanding is that it is fixed inasmuch as using the path with the mixture of `/` and `\` should work if you attempt to open the path and read it; readdir will still return paths with such a mixture of directory separator characters, but that shouldn't prevent you from interacting with it via this crate.

Having quickly scanned through this issue, I agree with the original sentiment that it feels confusing for readdir to return `PathBuf`, which is a local-os-dependent path representation, when that representation may not match that of the remote host and doesn't match that in the protocol spec.
