### ISSUE TITLE
sftp FUSE support 

### ISSUE THREAD

**Issue by steven004** [alexcrichton/ssh2-rs#144]
From the implementation in [sftp.rs](https://github.com/alexcrichton/ssh2-rs/blob/master/src/sftp.rs) , it looks like FUSE support, or close to FUSE support. 

@wez , any suggestion about how easily one could create a FUSE system via the sftp implemented in this project. Thanks.

**Comment by wez** [comment]
You could probably stick this crate together with https://docs.rs/fuse/ relatively easily.
To make a fuse filesystem work well requires some additional effort, so you'd need to have a good reason to put in that effort that rather than just use something like https://github.com/libfuse/sshfs.

**Comment by steven004** [comment]
Thanks Wez.
That makes sense. I still need to do something by myself. What I want to do
is to automatically link to a server to access a file via ftp or http
flexibly when there is a need. The client may access different servers
without a need to connect to a server when mounting. So, I think I need to
do connection while open a file, and close it when close a file.
