### ISSUE TITLE
How to passin mode parameter when call func request_pty()

### ISSUE THREAD

**Issue by zyc801208** [alexcrichton/ssh2-rs#145]
# My code is like this:
> //number '53' means ssh.ECHO, and 0x01 means echo on
let term_mode:  [u8; 5] = [53, 0, 0, 0, 0x01];
let dim = Some((10000, 100000, 10000, 10000));
let mode = str::from_utf8(&term_mode).unwrap();
chan.request_pty("xterm", Some(mode), dim).unwrap();
...
## I got error response down below after execute above code
_request_pty error: [-14] Failed to require the PTY package_
***
**My problem is how to assign a value to mode parameter about func request_pty()**
Thank you!

**Comment by wez** [comment]
It looks like the sparse documentation of libssh2 led to the type being declared incorrectly and treated as a utf8 string.  We'll need to fix that (https://tools.ietf.org/html/rfc4250#section-4.5 describes the usage of this parameter and we can make some stronger types for that), but you may be able to hack around it for now by doing something like this:

```rust
// Force the runtime to allow viewing this data through a `&str`, even
// though it isn't valid UTF-8
let mode_str = unsafe {
   std::str::from_utf8_unchecked(term_mode)
};

chan.request_pty("xterm", Some(mode_str), dim).unwrap();

```

**Comment by wez** [comment]
(I think you might also need to add an extra 0 byte at the end of the `term_mode` array to mark `TTY_OP_END`)

**Comment by wez** [comment]
On the `ptymode` branch that I just pushed is an experiment that I haven't tested (it compiles, but I haven't tried to actually use it).

You can try it out by changing your `Cargo.toml` file to point to it:

```
ssh2 = { git = "https://github.com/alexcrichton/ssh2-rs", branch = "ptymode" }
```

Then in your code, do something like this:

```rust

let mut mode = ssh2::PtyModes::new();
mode.set_boolean(ssh2::PtyModeOpcode::ECHO.into(), true);

chan.request_pty("xterm", Some(mode), dim).unwrap();
```
