### ISSUE TITLE
Yank breaking versions with "*" deps

### ISSUE THREAD

**Issue by kornelski** [alexcrichton/ssh2-rs#147]
Some old versions of `ssh2` have dependencies specified with `"*"` version requirement (`libssh2-sys = "*"`).

Crates with such vague dependency versions became unusable, because `*` allows picking too-new semver-incompatible dependencies.
It also breaks Cargo's `minimal-versions` feature, because `*` requirement allows picking very very old dependencies that aren't compatible with Rust 1.0.

Because these old versions of `ssh2` are unusable and cause problems for Cargo, I suggest yanking them:

```bash
cargo yank --vers 0.0.1
cargo yank --vers 0.0.2
```

**Comment by kornelski** [comment]
Same for `libssh2-sys` 

```bash
cargo yank --vers 0.0.1
```

**Comment by wez** [comment]
Yanked!
