### ISSUE TITLE
Firewall SSH server reply part

### ISSUE THREAD

**Issue by zyc801208** [alexcrichton/ssh2-rs#149]
My use case is send a command to firewall SSH server, and expect hundreds of kilobytes replied. 
But limited by Window size of pseudo terminal or other constraint unknown, my program always read part replying, suffix with "--More--", I need to send lots of space character(32) to remote side to get replying completely in this situation. 

1. How to read all replying in once time?
2. The second problem is read TimedOut calling Channel::read_to_end, and TcpStream is set in blocking mode.

Looking forward to your reply，thanks a lot.

**part code:**
--
    pub fn request_pty(&mut self) {
        //adjust dim to any value doesn't work
        let dim = (800, 240, 640, 480);
        let mut mode = ssh2::PtyModes::new();
        mode.set_boolean(ssh2::PtyModeOpcode::ECHO, true);
        mode.set_u32(ssh2::PtyModeOpcode::TTY_OP_ISPEED, 14400);
        mode.set_u32(ssh2::PtyModeOpcode::TTY_OP_OSPEED, 14400);

        if let Err(error) = self.inner.request_pty("xterm", Some(mode), Some(dim)) {
          error!("request_pty error: {}", format!("{}", error));
        }
        if let Err(error) = self.inner.shell() {
            error!("open shell mode error: {}", error);
        }
    }

**Test result**  
 > connect to remote_address: ####:## success
 > handshake success
 > auth with password success
 > Session: current session ip: ####:## fd: 7
 > **test_display_cur** create session elapsed: 1302 ms
 > write to server success, cmd: display current-configuration

 > channel read_window: 2097152, 0, 2097152
 > peek 10 bytes, elapsed 30 ms
 > reade 236709 bytes, error: Timed out waiting on socket, elapsed 40581 ms
 > **test_display_cur** elapsed: **42042** ms

**Comment by wez** [comment]
Can you tell the remote command to not use the pager?  Or not request a pty?
If not, how about running the remote command using `env PAGER=cat my-command`?

The fundamental issue is that you're trying to automate an interactive session, and it is complicated!
This issue has some discussion on that topic:
https://github.com/alexcrichton/ssh2-rs/issues/128

**Comment by zyc801208** [comment]
Firstly sorry about my poor english, I hope i can express the detail more clearly.
You said exactly right, my program run in interactive session, and it's  procedure is automation.
The device is hardware firewall device, it installed mini CentOS, and sshd service run in daemon.
In order to get information from the device, my program need to send some command，the device recognized, just like "show version" etc, all command my program sent is device exclusive。

The problem i encountered is just like shell command "less" or "more", displayed part content, and the content length is just follow to the size of windows or pseudo terminal(pty).
Now i need to get all content in one time.the number of IO interactions will be reduced, and the performance will be better.

Thanks a lot for your prompt reply.
