### ISSUE TITLE
Sessions are unable to be returned

### ISSUE THREAD

**Issue by bbatha** [alexcrichton/ssh2-rs#16]
I am try to write some code that will initialize a session in another function but it doesn't seem like a session is able to be returned, and I get a run time error when attempting to use it:

```rust
fn setup() -> Session {
        let tcp = TcpStream::connect("127.0.0.1:22").unwrap();
        let mut sess = Session::new().unwrap();
        sess.handshake(&tcp).unwrap();
        sess.userauth_agent("username").unwrap();
        sess
    }


#[test]
fn it_doesnt_work() {
        let mut sess = setup();
        let mut channel = sess.channel_session();
        match channel {
            Ok(_) => println!("Ok"),
            Err(x) => println!("{}", x),
        }
}
```

Results in the error:
"Error { code: -7, msg: "Unable to send channel-open request" }"

**Comment by alexcrichton** [comment]
Thanks for the report! This is currently one thing I'm not super enthused about in terms of the API, but [the documentation for `handshake`](http://alexcrichton.com/ssh2-rs/ssh2/struct.Session.html#method.handshake) points out that you need to make sure the `TcpStream` lives longer than the `Session` itself. I wanted to make as lightweight of a wrapper as possible around libssh2 so I didn't want to take ownership of the `TcpStream`, but I'd recommend keeping the `Session` and the `TcpStream` paired up when moving them around. After that though it should do the trick!
