### ISSUE TITLE
Slow SFTP downloads compared to regular `sftp` command

### ISSUE THREAD

**Issue by fgimian** [alexcrichton/ssh2-rs#166]
Hey there, thanks so much for your work on this library! 😄 

Here's my Rust code:

```rust
use std::net::TcpStream;
use std::fs::File;
use std::io;
use std::path::Path;
use std::time::SystemTime;
use chrono::offset::Local;
use chrono::DateTime;

fn main() {
    let tcp = TcpStream::connect("myhost:22").unwrap();
    let mut session = ssh2::Session::new().unwrap();
    session.set_tcp_stream(tcp);
    session.handshake().unwrap();
    session
        .userauth_pubkey_file(
            "fots",
            None,  // public key
            Path::new("id_rsa"),
            None,  // passphrase
        )
        .unwrap();

    let remote_path = Path::new("/data.csv.gz");
    let sftp = session.sftp().unwrap();

    let mut input_file = sftp.open(remote_path).unwrap();
    let mut output_file = File::create("copy").unwrap();
    io::copy(&mut input_file, &mut output_file).unwrap();
}
```

The problem is that I'm seeing significantly longer SFTP download times using this Rust code compared to the regular `sftp` command provided as part of the OpenSSH client.  In my case, for a roughly 250 MB file over the network, I see the following download times:

**OpenSSH SFTP client**: 1m6.469s
**Rust Version (pre-compiled in `--release` mode)**: 5m38.701s

Any ideas are greatly appreciated 😄 

Cheers
Fotis

**Comment by fgimian** [comment]
Interestingly, if I read the file myself with two different approaches, I get very different results:

```rust
    let mut big_buffer = Vec::new();
    file.read_to_end(&mut big_buffer).unwrap();
```

Using `read_to_end` is incredibly fast (around 50 secs).

```rust
    let mut buffer = [0; 8 * 1024];
    loop{
        let num_bytes = file.read(&mut buffer).unwrap();
        if num_bytes == 0 {
            break;
        }
    }
```

Reading in chunks of 8 kb takes 5 minutes (similar to that above).

Naturally, using `read_to_end` is impractical with a large file.

I'm hoping that I'm simply missing something obvious 😄 

Thanks again
Fotis

**Comment by fgimian** [comment]
Okies, I have found the cause of this problem.  The default buffer size of the `sftp` command as per its [man page](http://man7.org/linux/man-pages/man1/sftp.1.html) is **32,768 bytes** (32 kb).  The `io::copy` function seems to use an 8 kb buffer.

Implementing my own buffered copy using 32 kb chunks offers similar performance to `sftp` and going beyond that to around 1 MB shows further improvements.

While testing, I saw data packets of up to 510,000 bytes so it seems that a larger buffer size is indeed helpful.

Sadly, it's not possible to pass a buffer size into the `io::copy` function.

I'll post my code here tomorrow for other people's reference and then close the issue.

Kindest regards
Fotis

**Comment by wez** [comment]
Have you considered using [`BufReader::with_capacity`](https://doc.rust-lang.org/std/io/struct.BufReader.html#method.with_capacity) together with `io::copy`?  That may save you from having to get down in the weeds with your own buffering code:

```rust
let capacity = 1024 * 1024;
let mut input_file = io::BufReader::with_capacity(
     capacity,
     sftp.open(remote_path).unwrap());
let mut output_file = File::create("copy").unwrap();
io::copy(&mut input_file, &mut output_file).unwrap();
```

**Comment by wez** [comment]
(you may also want to use a `BufWriter` for the local file)

**Comment by fgimian** [comment]
@wez thank you so much, I can confirm that using a `BufReader` and `BufWriter` works perfectly.

I'll close this issue now 😄 
Fotis
