### ISSUE TITLE
Consider support zmodem protocol

### ISSUE THREAD

**Issue by zyc801208** [alexcrichton/ssh2-rs#168]
Do you consider support ZSSH? 
transfer file using rz/sz

**Comment by wez** [comment]
This rust crate wraps the underlying libssh2 library: https://www.libssh2.org/
It can only expose features provided by that library, as that is its purpose.  As such, no, we won't be implementing that here.

From the description of the zssh web page, it sounds like it is using zmodem layered over the top of ssh2.  You should be able to take an existing implementation of the zmodem protocol (perhaps inspired by https://github.com/lexxvir/zmodem) and layer it on top of the `Channel` type exposed by this crate to achieve a similar result in your own application.
