### ISSUE TITLE
Error when using scp_recv when the filename has spaces

### ISSUE THREAD

**Issue by tristan** [alexcrichton/ssh2-rs#177]
I have a problem using scp_recv when the filenames have spaces in them

e.g. I have the following code to download all the files in a given path
```
let tcp = TcpStream::connect(&host)?;
let mut session = Session::new()?;
session.set_tcp_stream(tcp);
session.handshake()?;
session.userauth_password(&username, &password)?;
let sftp = session.sftp()?;
for (filepath, _entry) in sftp.readdir(&data_path)? {
    let (remote_file, stat) = session.scp_recv(&filepath)?;
    // .... do file download
}
```
As soon as it hits a file with a space in the name, i get the following error
`Error { code: -28, msg: "Failed to recv file" }`

To work around the problem I had to add the following at the start of the for loop
```
    let filepath = if let Some(filepath) = filepath.to_str() {
        PathBuf::from(&filepath.replace(" ", "?"))
    } else {
        panic!("could not get {:?} as a string", filepath);
    };
```
Also, I first tried to use `"\\ "`, and `"\\\\ "` but that didn't seem to help (but i don't think it should be necessary to do this replace at all from paths coming from the `readdir` method).

Am I doing something wrong, or is there a bug somewhere? 

Thanks!

system: archlinux
system libssh2 version: 1.9.0
connecting to a sftp server with username/password

**Comment by wez** [comment]
I noticed that you're mixing sftp with scp.  I'd suggest doing something like this to get a handle on the file contents using your established sftp channel:

```rust
let remote_file = sftp.open(&filepath)?;
```

(see https://docs.rs/ssh2/0.8.0/ssh2/struct.Sftp.html#method.open)

**Comment by tristan** [comment]
Thanks for pointing that out @wez, using `sftp.open` works without my `.replace(" ", "?")` hack :tada: .

I also took the time to check this using a plain ssh server, and I don't have the same problem

e.g. this works fine for me
```
use std::io::prelude::*;
use std::net::TcpStream;
use ssh2::Session;
use std::path::Path;

fn main() -> Result<(), Box<dyn std::error::Error + Send + Sync>> {
    let host = "127.0.0.1:22";
    let tcp = TcpStream::connect(&host)?;
    let mut sess = Session::new()?;
    sess.set_tcp_stream(tcp);
    sess.handshake()?;
    sess.userauth_agent("tristan")?;

    let (mut remote_file, stat) = sess.scp_recv(
        Path::new("A file with spaces.txt")
    )?;
    println!("remote file size: {}", stat.size());
    let mut contents = Vec::new();
    remote_file.read_to_end(&mut contents)?;
    println!("{}", String::from_utf8(contents)?);

    Ok(())
}
```

So, this is not a problem with `scp_recv` but something to do with how sftp servers treat filenames, which I don't know enough about to comment on :sweat_smile: .
