### ISSUE TITLE
Unable get userauth_keyboard_interactive to work

### ISSUE THREAD

**Issue by ellishg** [alexcrichton/ssh2-rs#178]
I'm not sure if I am doing something wrong or if there is a bug, but I can't authenticate using `session::userauth_keyboard_interactive`. [This](https://github.com/ellishg/rftp/blob/278a07633dbecb36037f7edd4e544aee41810403/src/rftp.rs#L283) is what I have tried.

```rust
struct Prompter;
impl ssh2::KeyboardInteractivePrompt for Prompter {
    fn prompt(
        &mut self,
        username: &str,
        instructions: &str,
        prompts: &[ssh2::Prompt],
    ) -> Vec<String> {
        println!("I expect something to be printed here.");
        println!("{}", username);
        println!("{}", instructions);
        prompts.iter().map(|p| p.text.to_string()).collect()
    }
}
let mut prompter = Prompter;
session.userauth_keyboard_interactive(username, &mut prompter)?;
```

It would be helpful if there was a little more explanation and a working example in the docs.

**Comment by wez** [comment]
Here's a working example from inside wezterm:

https://github.com/wez/wezterm/blob/master/src/ssh.rs#L172

the prompter implementation is towards the top of that file: https://github.com/wez/wezterm/blob/master/src/ssh.rs#L18

**Comment by wez** [comment]
I think one of the things that is confusing is that `password` auth is not the same thing as `keyboard-interactive` auth, even though both can appear similar when prompting the user.

Another thing that is confusing is that the `auth_methods` can change based on the results of authenticating; for example, at my place of work, I have to `password` auth before `keyboard-interactive` is offered and allows me to use a yubikey as a second factor of authentication.

I'd also recommend that you move your host key check to happen before you prompt the user to enter a password; that way have a chance to detect a MITM or compromised remote system before you pass the users credentials to the host.

**Comment by ellishg** [comment]
That makes more sense, I'll take a look at your implementation. 

Thanks for catching that MITM bug!
