### ISSUE TITLE
How do I get stderr output and escape characters?

### ISSUE THREAD

**Issue by spencerkohan** [alexcrichton/ssh2-rs#179]
When I execute a command via a channel like so:

```
    let channel = &mut self.session.channel_session().unwrap();
    channel.exec(
        &cmd
    ).unwrap();
    let mut s = String::new();
    channel.read_to_string(&mut s).unwrap();
```

I only get the plain text which is coming through stdout.  Ideally I would like to preserve colors (escape codes) and the content of stderr.  Is this possible with this library?

**Comment by spencerkohan** [comment]
Also is it possible to get stdout as a stream?

**Comment by wez** [comment]
You didn't include any specifics on what command you are actually running, so this is going to be a generic answer.

Many tools will default to not emitting escape sequences when they detect that they are not connected to a TTY (Terminal TeletYpe).   `ls --color=auto` is one example of this.

Some tools will allow you to force the use of color even when the output is not a tty.  `ls --color=always` is one example of this.

If what you're running doesn't allow forcing escape sequences into its output then you will need to ask the SSH server to allocate a *Pseudo Terminal teletYpe* (PTY), which is a virtualized TTY.   You use https://docs.rs/ssh2/0.8.0/ssh2/struct.Channel.html#method.request_pty to do this.

You can use https://docs.rs/ssh2/0.8.0/ssh2/struct.Channel.html#method.stderr to get the stderr stream.

You can use https://docs.rs/ssh2/0.8.0/ssh2/struct.Channel.html#method.stream with stream id `0` to get a stream handle for `stdout`.

**Comment by chaosmatrix** [comment]
I have same question.

what i want to do is `match prompt message then input password(write some text in stdin)`, then show command exec output, stderr(`if directory /path exist`) and stdout(`if directory /path not exist`).


consider this code:
```
let mut _channel = _session.channel_session()?;
_channel.request_pty("xterm", None, None)?;
_channel.exec("sudo su - -c 'ls /path'")?;
loop {
    let mut _stdout = vec![0u8; 512];
    let mut _stderr = vec![0u8; 512];
    match (_channel.stream(0).read(&mut _stdout), _channel.stderr().read(&mut _stderr) {
        (Ok(_osize), Ok(_esize)) => {
             // handle stdout
             print!("{:?}\n", _stdout);
             // handle stderr
             print!("{:?}\n", _stderr);
             // do prompt message match, then send input
             if _promtp_message_match() {
                 _channel.write_all("password\n"); 
             }
             ...
        }
        ...
    }
}
```

above code didn't work, prompt message such like `Password: ` can't be read from stdout, and `stderr stream` always empty, even if directory `/path` not exist, which should generate stderr message.

**Comment by wez** [comment]
@chaosmatrix that's not the same question at all :-p   Please see the discussion on https://github.com/alexcrichton/ssh2-rs/issues/128
