### ISSUE TITLE
no method named `read_to_string` found for struct `ssh2::channel::Channel`

### ISSUE THREAD

**Issue by bernardoaraujor** [alexcrichton/ssh2-rs#188]
```
[dependencies]
ssh2 = "0.8"
```

Trying to execute this under Fedora 30:
```rust
use std::net::TcpStream;
use ssh2::Session;

fn main() {
    // Connect to the local SSH server
    let tcp = TcpStream::connect("192.168.1.141:22").unwrap();
    let mut sess = Session::new().unwrap();
    sess.set_tcp_stream(tcp);
    sess.handshake().unwrap();

    sess.userauth_password("username", "password").unwrap();
    assert!(sess.authenticated());

    let mut channel = sess.channel_session().unwrap();
    channel.exec("ls").unwrap();
    let mut s = String::new();
    channel.read_to_string(&mut s).unwrap();
    println!("{}", s);
    channel.wait_close();
    println!("{}", channel.exit_status().unwrap());
}
```

I get this error:
```cargo
   Compiling beekeeper v0.0.1 (/home/bernardo/dev/beekeeper)
error[E0599]: no method named `read_to_string` found for struct `ssh2::channel::Channel` in the current scope
  --> src/main.rs:17:13
   |
17 |     channel.read_to_string(&mut s).unwrap();
   |             ^^^^^^^^^^^^^^ method not found in `ssh2::channel::Channel`
   |
   = help: items from traits can only be used if the trait is in scope
help: the following trait is implemented but not in scope; perhaps add a `use` for it:
   |
1  | use std::io::Read;
   |

error: aborting due to previous error

For more information about this error, try `rustc --explain E0599`.
error: could not compile `beekeeper`.

To learn more, run the command again with --verbose.
```

I inspected https://github.com/alexcrichton/ssh2-rs/blob/0.8.0/src/channel.rs and found no declaration of `read_to_string()`, only a reference of usage in the form of comment (line [235](https://github.com/alexcrichton/ssh2-rs/blob/2e0d3cd7f9b8673b7a85195bc8dedad34fcdce62/src/channel.rs#L235)).

**Comment by wez** [comment]
The `read_to_string` method is defined by the trait `std::io::Read`.  The way the trait is defined, the `Channel` struct in this crate only needs to implement the [read](https://github.com/alexcrichton/ssh2-rs/blob/0.8.0/src/channel.rs#L483) method with the rest of the trait being implemented in terms of `read` its definition in the rust standard library.

The help portion of the error message that you shared tells you what you need to do; add:

```
use std::io::Read;
```

to bring the trait into scope so that the compiler can see the method.

**Comment by bernardoaraujor** [comment]
Rust beginner here.
Adding `use std::io::Read;` fixed the problem.

Thank you 🙏
