### ISSUE TITLE
A more elaborate client

### ISSUE THREAD

**Issue by arieb** [alexcrichton/ssh2-rs#190]
Hello, 
im relatively new to Rust,  and im trying to implement a client that opens a pty and shell on a server, that also uses ssh_select to properly check when data is available to be read and written:
see the section of "A more elaborate way to get the remote data" in the official libssh docs
https://api.libssh.org/stable/libssh_tutor_shell.html#opening_shell

looking at the code, im not sure whats the best way to achieve this using these binding - any help is appreciated

**Comment by wez** [comment]
There's some discussion about this on https://github.com/alexcrichton/ssh2-rs/issues/128
