### ISSUE TITLE
Out of Date Documentation And Some Failing Functionality

### ISSUE THREAD

**Issue by rackertest** [alexcrichton/ssh2-rs#194]
I’m not sure if this is the right place to submit bugs in this crate's  documentation, but I found some in the following page:
 
https://docs.rs/ssh2/0.3.1/ssh2

Most of them just need to have sess.handshake(&tcp).unwrap() changed to sess.handshake().unwrap(). Otherwise they won’t even compile. This particular example for uploading a file seems worse:
use std::io::prelude::*;
use std::net::TcpStream;
use std::path::Path;
use ssh2::Session;

// Connect to the local SSH server
let tcp = TcpStream::connect("127.0.0.1:22").unwrap();
let mut sess = Session::new().unwrap();
sess.handshake(&tcp).unwrap();
sess.userauth_agent("username").unwrap();

let mut remote_file = sess.scp_send(Path::new("remote"),
                                    0o644, 10, None).unwrap();
remote_file.write(b"1234567890").unwrap();

I corrected sess.handshake().unwrap(). I also had to add in sess.set_tcp_stream(tcp); for this to compile. Then it seemed to run, but did not copy any files. I experienced between with an Arch Linux host and Debian vm. I doubt this matters, but just some information if you need to reproduce what I’m seeing. I also confirmed the ssh and rsync utilities worked between these two devices before trying to run the code mentioned. 

Anyway to get this running?

**Comment by wez** [comment]
You're looking at the docs for version 0.3.  There's a link in orange at the top of the page that will take you to do the docs for the latest version.

**Comment by rackertest** [comment]
Well, it does seem I was looking at the wrong page and the newer documentation compiles correctly. However, it still doesn't copy a file or even produce an error. I don't see a destination path, but I made a pretty distinct file name and a system wide search on the destination does not find it:

$ locate -c ljsdlkxxldjwed
0

I thought the 'b' before the filename might be binary only files, but copying a binary didn't work either. I even tried specifying the full path, but no change.

Are you able to confirm this code does copy files?

**Comment by crisidev** [comment]
The example above should work, but it is an example and will not work in certain conditions, as scp requires you to close the channel to ensure the file is actually written. See here https://github.com/alexcrichton/ssh2-rs/issues/79#issuecomment-613632652 for a better example.

**Comment by crisidev** [comment]
See https://github.com/alexcrichton/ssh2-rs/pull/202

**Comment by crisidev** [comment]
I am going to resolve this as we updated the documentation and I tested the example and it is working.
