### ISSUE TITLE
Windows MSVC build: "Unable to exchange encryption keys"

### ISSUE THREAD

**Issue by CraZySacX** [alexcrichton/ssh2-rs#20]
The following code below successfully authenticates when built on Linux.   When built with the MSVC build on windows it fails at the handshake with:

```
["diffie-hellman-group14-sha1", "diffie-hellman-group-exchange-sha1", "diffie-hellman-group1-sha1"]
["ssh-rsa", "ssh-dss"]
["aes256-cbc", "rijndael-cbc@lysator.liu.se", "aes192-cbc", "aes128-cbc", "arcfour128", "arcfour", "3des-cbc"]
ERROR: Error { code: -5, msg: "Unable to exchange encryption keys" }
```
I've verified that the server supports all three of the key exchange types.  I also built ssh2-rs against libssh2 1.6.0 as they had fixed some WinCG bugs, but that also resulted in the same error.  I could try and gather more debugging info on the client side, but I'm not sure how to configure libssh2 to spit out more info.

```rust
extern crate mush as ssh2;

use ssh2::Session;
use std::net::TcpStream;

use ssh2::MethodType::*;

fn main() {
    // Connect to the local SSH server
    let tcp = TcpStream::connect("aservericonnecto:22").unwrap();
    let mut sess = Session::new().unwrap();

    match sess.supported_algs(Kex) {
        Ok(res) => {
            println!("{:?}", res);
        },
        Err(e) => {
            println!("ERROR: {:?}", e);
            return
        }
    }

    match sess.supported_algs(HostKey) {
        Ok(res) => {
            println!("{:?}", res);
        },
        Err(e) => {
            println!("ERROR: {:?}", e);
            return
        }
    }

    match sess.supported_algs(CryptCs) {
        Ok(res) => {
            println!("{:?}", res);
        },
        Err(e) => {
            println!("ERROR: {:?}", e);
            return
        }
    }

    // Errors out here on Windows MSVC build
    match sess.handshake(&tcp) {
        Ok(_) => {},
        Err(e) => {
            println!("ERROR: {:?}", e);
            return
        }
    }

    // Try to authenticate with the first identity in the agent.
    match sess.userauth_agent("username") {
        Ok(_) => {}
        Err(e) => println!("ERROR: {:?}", e),
    }

    // Make sure we succeeded
    assert!(sess.authenticated());
}
```

**Comment by alexcrichton** [comment]
Unfortunately I'm not sure if there's a whole lot this library can do about this, it sounds like this may be a bug in either libssh2 or the usage of libssh2? If there's some various build flags or such that need to be provided, then we can definitely add it to the build script, but otherwise I'm not quite sure what to do here?

**Comment by CraZySacX** [comment]
I agree. I'll try and see if I can figure out on that side what is going on.  I was able to confirm that the library could see the keys properly in pageant, and the tcp connection is writable.  I also made sure I didn't have any extra unix-ish executables on my path from git-bash and msys2.   Maybe I'll just stick to Linux builds :)

**Comment by alexcrichton** [comment]
Ok!

**Comment by CraZySacX** [comment]
Seems to be a problem with wincng in libssh2.  I finally cobbled together a libssh2 build with openssl and everything works as expected.

**Comment by alexcrichton** [comment]
Ah ok, in that case I'll close this as an upstream bug, but if there's a fix upstream that can be included locally just let me know and I'll update the bundled version!

**Comment by alexcrichton** [comment]
Ah ok, in that case I'll close this as an upstream bug, but if there's a fix upstream that can be included locally just let me know and I'll update the bundled version!

**Comment by kdar** [comment]
I ran into this same issue using ssh2-rs on 64bit windows on the mingw64 toolchain (in msys2). I had to edit libssh2-sys/build.rs and force it to use OpenSSL instead of WinCNG on windows:

```
 // Don't use OpenSSL on Windows, instead use the native Windows backend.
  // if target.contains("windows") {
  //    cfg.define("CRYPTO_BACKEND", "WinCNG");
  // } else {
        cfg.define("CRYPTO_BACKEND", "OpenSSL");
  // }
```

Maybe it might be helpful to have an env variable we can configure to force it to use OpenSSL on windows, noting in the README that if you run into this sort of problem, you can attempt linking with OpenSSL instead.

**Comment by alexcrichton** [comment]
Ah yeah I won't mind having a config var to switch MinGW builds to OpenSSL

**Comment by alexcrichton** [comment]
it may be worth doing so as an optional dependency which is off-by-default on Windows

**Comment by Zerowalker** [comment]
I am stuck with this as well, i can't really figure out how to build using OpenSSL instead.
