### ISSUE TITLE
libssh2 multiple channels concurrent issue

### ISSUE THREAD

**Issue by jason-ni** [alexcrichton/ssh2-rs#201]
I'm trying to implement a remote port forwarding proxy using async-ssh2. The core idea can be expressed like bellow code:
```
use async_ssh2::{Channel, Session};
use futures_util::io::AsyncReadExt;
use smol::io::copy;
use smol::Async;
use std::net::SocketAddr;
use std::net::TcpStream;

async fn do_proxy(tcp_conn: Async<TcpStream>, ch: Channel) -> Result<(), anyhow::Error> {
    let (ch_rh, ch_wh) = ch.split();
    let (conn_rh, conn_wh) = tcp_conn.split();
    smol::future::or(copy(ch_rh, conn_wh), copy(conn_rh, ch_wh))
        .await
        .map_err(|e| {
            println!("copy error: {:?}", e.raw_os_error());
        });
    Ok(())
}
```
Then I find concurrent connections to the remote port cause ssh2 channel read error at the copy point, and "Channel not found" error at the accept point.

After some investigation, I find a mail about the limitation of libssh2 multiple channels concurrent issue: https://www.libssh2.org/mail/libssh2-devel-archive-2014-06/0028.shtml

Maybe I need to ask in that mail thread directly. But before that, I would like to know are there anyone else have tried ssh2-rs remote port forwarding in a concurrent way?

**Comment by crisidev** [comment]
I would say you will find more luck by replying in the email thread and also opening an issue to https://github.com/spebern/async-ssh2 since this error happens when using that library and the async model that comes with it.

**Comment by jason-ni** [comment]
Thanks for your suggestion. I have replied in that thread and get confirmation that there's no improvement since then. So it's still broken when using epoll with libssh2. 
I indeed created a same issue to async-ssh2 but not get any response yet. 
Just wondering how do you guys use this ssh2-rs wrapper? Any other async model work beside async-ssh2?

**Comment by crisidev** [comment]
I am personally using only the sync version, so I cannot really help here :(

**Comment by jason-ni** [comment]
Thanks. It seems a cold topic without much attention. I'm working on thrussh to achieve my goal. If anyone have interest in async and pure Rust, I suggest you have a look of thrussh.
