### ISSUE TITLE
SFTP is way too slow when using Read and Write methods

### ISSUE THREAD

**Issue by ChristianVisintin** [alexcrichton/ssh2-rs#206]
Hi there,

This issue is not new to this project actually, but I don't know why it has been closed, since the issue hasn't been solved at all.
The regarding issue is #166
The difference here is that this issue happens also with `write` and `read`.

Basically I have a method which opens the remote file for write:

```rust
fn send_file(
        &mut self,
        local: &FsFile,
        file_name: &Path,
    ) -> Result<Box<dyn Write>, FileTransferError> {
        match self.sftp.as_ref() {
            None => Err(FileTransferError::new(
                FileTransferErrorType::UninitializedSession,
            )),
            Some(sftp) => {
                let remote_path: PathBuf = self.get_abs_path(file_name);
                // Calculate file mode
                let mode: i32 = match local.unix_pex {
                    None => 0o644,
                    Some((u, g, o)) => ((u as i32) << 6) + ((g as i32) << 3) + (o as i32),
                };
                match sftp.open_mode(
                    remote_path.as_path(),
                    OpenFlags::WRITE | OpenFlags::CREATE | OpenFlags::APPEND | OpenFlags::TRUNCATE,
                    mode,
                    OpenType::File,
                ) {
                    Ok(file) => Ok(Box::new(BufWriter::with_capacity(8192, file))),
                    Err(err) => Err(FileTransferError::new_ex(
                        FileTransferErrorType::FileCreateDenied,
                        format!("{}", err),
                    )),
                }
            }
        }
    }
```

Then the calling method receives the `Write` trait in a `Box` and just writes data from a local file using buffers with size `8192`.

```rust
loop {
    // Read till you can
    let mut buffer: [u8; 8192] = [0; 8192];
    match fhnd.read(&mut buffer) {
        Ok(bytes_read) => {
            total_bytes_written += bytes_read;
            if bytes_read == 0 {
                break;
            } else {
                // Write bytes
                if let Err(err) = rhnd.write(&buffer[0..bytes_read]) {
                    /* ... */
                }
            }
        }
        Err(err) => {  /* ... */      }
    }
}
```

---

The code which writes the stream, is the same which, based on the user configuration, works with an FTP stream or with an SCP file returned by the library function `scp_send`.

Theorically, the performance of SCP and SFTP should be almost the same, but not in this case.
I'm sending a file with size of **64MB** to a machine in my local network (ethernet, speed 100mbps).
When using SCP it takes `9.50` seconds to write the file to the remote machine, which is pretty good. With scp command line tool it takes 7 seconds for me, so it's good, especially considering that my implementation performs other operations at each write cycle.
On the other hand, when using **SFTP**, the **same file** (and I repeat: also the same code), takes `44.81` seconds to be written to the **same** remote machine.

I also tried to wrap the SFTP file handler into a `BufWriter`, but nothing has really changed (maybe improved the performance by 5%).

The same phenomenon happens when reading files from remote: SCP is fast as it should be, while SFTP is way slower (I must admit, when reading is anyway much faster than when writing, but anyway, still slow).

I'm then asking you, if this is a problem of my code, or if there is actually something blocking the I/O when using SFTP.
Could you please check?

Best regards,
Christian

**Comment by wez** [comment]
Regarding `BufWriter`: if the file handle you are reading from gives you lots of small fragmented reads then it makes sense to use `BufWriter`.  If the source file handle is a regular file then the structure of your copy loop means that it won't give a huge benefit.

However: pay attention to short writes in your copy loop.  In general, any write can succeed but write less than you requested, leaving a remnant for you to write as a follow up.  If you don't handle that case then you'll end up effectively corrupting the destination.

Regarding performance: you've selected 8192 bytes for your buffer size, but the discussion on the issue that you linked to says that a larger buffer size is better.

Why is bigger better?  Consider that each time you call `write` the ssh session needs to do some book-keeping and produce an encrypted packet to send to the other side, each of these has a certain amount of overhead for both the sender and the receiver.   If you have 64MB of data and split it into 8KB chunks there will be more of those to send to the remote than if you used a larger buffer size.   The reality is a bit more complicated as there is a windowing/scaling system in the ssh protocol that I confess to not fully understanding, but the upshot of it is that bigger is better, up until a point, after which making the buffer larger will have diminishing returns.

What should you do?  My general recommendation would be something like this so that you can control the effective buffer size; have a `BufWriter` with a larger internal buffer than the default used by `std::io::copy` will result in fewer calls to the underlying `write` in the ssh protocol.

```rust
/// Use large buffers for the copy operation, leaving it to std::io::copy to handle the slightly
/// fiddly short read/write cases.
/// As-written, this will consume the input handles, but you could decompose this and just
/// wrap them up elsewhere in the program
fn copy_with_large_buffer<R, W>(
  source: R,
  destination: W,
  buf_size: usize
) -> std::io::Result<u64> 
where
  R: Read,
  W: Write
{
   let source = BufReader::with_capacity(buf_size, source);
   let destination = BufWriter::with_capacity(buf_size, destination);
   std::io::copy(source, destination)
}

copy_with_large_buffer(fhnd, rhnd, 32*1024)?;
```

**Comment by ChristianVisintin** [comment]
I managed to increase the buffer size to 65536 (and to solve problems related to my write process, which didn't check the `write` return value). The process takes now half the time it used to take before. Now indeed to write 64MB it takes up to 20 seconds, which is decent, but still, double of scp.

In my opinion there is something which is wrong with the Sftp IO. I'd like to know why the same code, using a file handler retrieved from `scp_send` takes half of the time, while the file handler returned by `open_mode` doesn't.

Using copy doesn't make any difference:

```rs
// with fhnd as File
let mut fhnd = BufReader::with_capacity(65536, fhnd);
while total_bytes_written < file_size {
    match std::io::copy(&mut fhnd, &mut rhnd) {
        Ok(sz) => total_bytes_written += sz as usize,
        Err(err) => 
        {
            self.log(
            LogLevel::Error,
            format!("Could not read local file: {}", err).as_ref(),
            );
            self.input_mode = InputMode::Popup(PopupType::Alert(
                Color::Red,
                format!("Could not read local file: {}", err),
            ));
        }
    }
}
```

It still takes the same time it usually takes using write.

**Comment by ChristianVisintin** [comment]
After further investigations, I was able to solve the issue using a buffer of size `65536`.
And yes, my bad of course, even if there is a strange behaviour of SFTP when using some buffer sizes actually.

I've written a basic program to make the speedtests and I've tested different combinations.

```rs
extern crate ssh2;
extern crate tempfile;

use ssh2::{Session, Sftp};
use std::env;
use std::io::{BufReader, Read, Write};
use std::net::TcpStream;
use std::path::PathBuf;
use std::process::exit;
use std::time::Instant;

const BUFSIZE: usize = 65536;

fn write_stream(
    src: &mut BufReader<Box<dyn Read>>,
    dst: &mut tempfile::SpooledTempFile,
    file_size: usize,
) -> Result<(), std::io::Error> {
    let mut total_bytes_written: usize = 0;
    while total_bytes_written < file_size {
        // Read till you can
        let mut buffer: [u8; BUFSIZE] = [0; BUFSIZE];
        match src.read(&mut buffer) {
            Ok(bytes_read) => {
                total_bytes_written += bytes_read;
                if bytes_read == 0 {
                    continue;
                } else {
                    let mut buf_start: usize = 0;
                    while buf_start < bytes_read {
                        // Write bytes
                        match dst.write(&buffer[buf_start..bytes_read]) {
                            Ok(bytes) => buf_start += bytes,
                            Err(err) => {
                                return Err(err);
                            }
                        }
                    }
                }
            }
            Err(err) => return Err(err),
        }
    }
    Ok(())
}

fn main() {
    let args: Vec<String> = env::args().collect();
    if args.len() < 4 {
        eprintln!(
            "Usage: {} <address> <username> <password> <file_path>",
            args.get(0).unwrap()
        );
        exit(255);
    }
    let address: String = args.get(1).unwrap().clone();
    let file_path: PathBuf = PathBuf::from(args.get(4).unwrap().as_str());
    const SSH_PORT: u16 = 22;
    // Create session
    // Create session
    println!("Connecting to {}:{}", address, SSH_PORT);
    let tcp = TcpStream::connect(format!("{}:{}", address, SSH_PORT)).unwrap();
    // Create session
    let mut session = Session::new().unwrap();
    session.set_tcp_stream(tcp);
    session.handshake().unwrap();
    if let Err(err) =
        session.userauth_password(args.get(2).unwrap().as_str(), args.get(3).unwrap().as_str())
    {
        eprintln!("Could not connect to remote: {}", err);
        exit(1);
    }
    println!("Authentication succeeded");
    // Set blocking to true
    session.set_blocking(true);
    // Get SFTP
    let sftp: Sftp = session.sftp().ok().unwrap();
    // Create tempfile
    let mut sftp_dest: tempfile::SpooledTempFile = tempfile::SpooledTempFile::new(64 * 1024 * 1024); // 64MB
    let mut scp_dest: tempfile::SpooledTempFile = tempfile::SpooledTempFile::new(64 * 1024 * 1024); // 64MB
    // Get file size
    let file_size: usize = match sftp.stat(file_path.as_path()) {
        Ok(metadata) => metadata.size.unwrap() as usize,
        Err(err) => {
            eprintln!("Could not stat remote file: {}", err);
            exit(1);
        }
    };
    println!("File has size {}", file_size);
    let mut sftp_stream: BufReader<Box<dyn Read>> = match sftp.open(file_path.as_path()) {
        Ok(f) => BufReader::with_capacity(BUFSIZE, Box::new(f)),
        Err(err) => {
            eprintln!("Could not open remote file: {}", err);
            exit(1);
        }
    };
    println!("Downloading \"{}\" using SFTP...", file_path.display());
    let t_start: Instant = Instant::now();
    // Write to tempfile
    if let Err(err) = write_stream(&mut sftp_stream, &mut sftp_dest, file_size) {
        eprintln!("Could not write file: {}", err);
        exit(1);
    }
    println!("SFTP write took {}ms", t_start.elapsed().as_millis());
    // Now do the same thing using scp
    println!("Downloading \"{}\" using SCP...", file_path.display());
    let mut scp_stream: BufReader<Box<dyn Read>> = match session.scp_recv(file_path.as_path()) {
        Ok(f) => BufReader::with_capacity(BUFSIZE, Box::new(f.0)),
        Err(err) => {
            eprintln!("Could not open remote file: {}", err);
            exit(1);
        }
    };
    let t_start: Instant = Instant::now();
    // Write to tempfile
    if let Err(err) = write_stream(&mut scp_stream, &mut scp_dest, file_size) {
        eprintln!("Could not write file: {}", err);
        exit(1);
    }
    println!("SCP write took {}ms", t_start.elapsed().as_millis());
    session.disconnect(None, "Mandi!", None).unwrap();
    println!("Disconnected from remote");
}
```

I've noticed that using 65536 as bufsize, the speed difference between downloading file using SFTP and SCP is minimum:

32MB

```txt
Authentication succeeded
File has size 33554432
Downloading "/tmp/32m.dat" using SFTP...
SFTP write took 2874ms
Downloading "/tmp/32m.dat" usingn SCP...
SCP write took 2866ms
Disconnected from remote
```

256MB

```txt
Authentication succeeded
File has size 268435456
Downloading "/tmp/256m.dat" using SFTP...
SFTP write took 22967ms
Downloading "/tmp/256m.dat" usingn SCP...
SCP write took 22895ms
Disconnected from remote
```

While has a bigger offset when using for example `8192` as buffer size

```txt
Authentication succeeded
File has size 67108864
Downloading "/tmp/64m.dat" using SFTP...
SFTP write took 8043ms
Downloading "/tmp/64m.dat" using SCP...
SCP write took 5723ms
Disconnected from remote
```

Pretty much the same when using `2048` as buffer size

```txt
Authentication succeeded
File has size 67108864
Downloading "/tmp/64m.dat" using SFTP...
SFTP write took 6347ms
Downloading "/tmp/64m.dat" using SCP...
SCP write took 5729ms
Disconnected from remote
```

while a total disaster when using `4096`

```txt
Authentication succeeded
File has size 67108864
Downloading "/tmp/64m.dat" using SFTP...
SFTP write took 19288ms
Downloading "/tmp/64m.dat" using SCP...
SCP write took 5753ms
Disconnected from remote
```

I think that's very curious actually, and I think it would be interesting discovering why this happens, but yeah, with `65536` works fine for me, even if there is also little offset in performance, but nothing I should be worried for.

| Size (MB) | SFTP (seconds) | SCP (seconds) |
|-----------|----------------|---------------|
| 32        | 3.159          | 3.039         |
| 64        | 6.320          | 5.742         |
| 128       | 12.856         | 11.472        |
| 256       | 24.107         | 23.065        |
| 512       | 47.435         | 46.092        |
| 1024      | 93.589         | 91.991        |

**Comment by yodaldevoid** [comment]
> I believe this shall be added to the tests, or maybe in the readme or as example at least for any new user. I've been using (naively) [`write_all` from the tests](https://github.com/alexcrichton/ssh2-rs/blob/master/tests/all/sftp.rs#L29) and was getting some timeouts on larger files (~20+ Kb)

If you would like to submit a PR, we would appreciate it.
