### ISSUE TITLE
Session documentation refers to tcp_stream() which isn't defined

### ISSUE THREAD

**Issue by rtyler** [alexcrichton/ssh2-rs#208]
set_tcp_stream() doesn't appear to have the corollary `tcp_stream()` method to get the raw fd back out again.

**Comment by crisidev** [comment]
The TCP stream is owned by the session and getting it is an unsafe operation if I remember this properly. I am not with my laptop, so i am going by memory. 

What is the usecase of getting back the raw fd? I am asking to understand this better and try to find a good solution 🙂

**Comment by rtyler** [comment]
I'm not sure I have a good usecase, I think the lack of a "close" operation made me go looking for this. Seems that the right way to "close" is just "disconnect" and then drop as far as I can tell

**Comment by crisidev** [comment]
Precisely, just disconnect the session and underlying TCP stream will be closed. I'll look into this as soon as I am back from holidays to see if it makes sense to expose the underlying FD. However there is no need to close the TCP session manually.

**Comment by crisidev** [comment]
Honestly I don't think it is wise to expose the underlying TCP FD without a good usecase for it. The TCP stream is completely handled for you by the library.

**Comment by rtyler** [comment]
@crisidev generally I agree, this is really a ticket about a bug in documentation, not a suggestion to give me more foot-guns :smile:
