### ISSUE TITLE
Is there a way to tell `Session` to do user auth with `~/.ssh/config`?

### ISSUE THREAD

**Issue by azriel-myob** [alexcrichton/ssh2-rs#211]
Heya, is there a way to get [`Session`](https://docs.rs/ssh2/0.9.1/ssh2/struct.Session.html) to do user auth using parameters from `~/.ssh/config`?

I can't seem to find a way to do this, so have been using the [`Session#userauth_pubkey_file`](https://docs.rs/ssh2/0.9.1/ssh2/struct.Session.html#method.userauth_pubkey_file) method to directly pass in the user's private key.

I couldn't find if libssh2 actually provides an API method to tell it what SSH config file to use either.

---

**edit:** Ah, I think I understand now -- `~/.ssh/config` is a concept from `libssh`, not `libssh2`.

**Comment by crisidev** [comment]
I don't think libssh2 supports that..

**Comment by azriel-myob** [comment]
Yeap, I *just* realized / learnt that 😅. Shall have to decide whether to build a bridge, or use `libssh`.

Thanks ✌️
