### ISSUE TITLE
Should userauth_pubkey_memory test for openssl usage instead of Unix

### ISSUE THREAD

**Issue by WilliamABradley** [alexcrichton/ssh2-rs#238]
With the support of openssl on win32: https://github.com/alexcrichton/ssh2-rs/pull/216

This should enable us to use the openssl-based functions, such as `userauth_pubkey_memory` right?

Instead of `#[cfg(unix)]` it should be `#[cfg(LIBSSH2_OPENSSL)]` instead?
https://github.com/alexcrichton/ssh2-rs/blob/b5ada428daad8c52f70324bb19bd3d02c6a7cbfb/src/session.rs#L517-L529

**Comment by rewik** [comment]
This would be quite helpful to me, I'm currently using a local copy of ssh2-rs with a patch that allows this.
