### ISSUE TITLE
Translate `LIBSSH2_FX_NO_SUCH_FILE` and `LIBSSH2_FX_NO_SUCH_PATH ` to `io::ErrorKind::NotFound`.

### ISSUE THREAD

**Issue by sourcefrog** [alexcrichton/ssh2-rs#244]
https://github.com/alexcrichton/ssh2-rs/blob/b5ada428daad8c52f70324bb19bd3d02c6a7cbfb/src/error.rs#L211-L220

A "file not found" from the server, when translated to an `io::Error` comes out as `IOError { source: Custom { kind: Other, error: "no such file" } }`.

It would be nice if this was instead translate to [`NotFound`](https://doc.rust-lang.org/std/io/enum.ErrorKind.html#variant.NotFound).

Any objection to a PR for this?

**Comment by yodaldevoid** [comment]
If you would like to submit a PR for this, I think it is a good idea.

For what it's worth, in the future feel free to simply submit the PR, especially for a small thing like this.

**Comment by sourcefrog** [comment]
Thanks, will do, feel free to assign it.
