### ISSUE TITLE
Build failure on aarch64 android

### ISSUE THREAD

**Issue by nabijaczleweli** [alexcrichton/ssh2-rs#256]
Forwarded from https://github.com/nabijaczleweli/cargo-update/issues/184, ssh2-rs 0.2.23: https://github.com/nabijaczleweli/cargo-update/files/9399718/error.txt

**Comment by AlexCzar** [comment]
Hi, I'm the author of the original issue.
I've also tried to build ssh2-rs standalone from source, used the latest commit in master branch. Result is attached. 
[6cf34b42e96cacd9ccbcb00e07cb8d5b84049041.build.log](https://github.com/alexcrichton/ssh2-rs/files/9414842/6cf34b42e96cacd9ccbcb00e07cb8d5b84049041.build.log)

**Comment by yodaldevoid** [comment]
@AlexCzar This looks like a build failure with libssh2, specifically it can't find `aarch64-linux-android-ar`. What toolchain are you using? Are you building from a Windows or a Linux machine (though this shouldn't matter)?

**Comment by AlexCzar** [comment]
Hi, I'm using Termux on Android (aarch64).
I've found a solution, to be able to compile I need to install compatible `binutils` and use `llvm-ar`:
```bash
; pkg install binutils-is-llvm
; AR=llvm-ar cargo install cargo-update
```
