### ISSUE TITLE
Communication with github failing

### ISSUE THREAD

**Issue by darakeon** [alexcrichton/ssh2-rs#258]
I had a problem using git2 rust library. Seems to be something about ssh communication with github.

git2 issue: https://github.com/rust-lang/git2-rs/issues/872

Is there a way to know if version 0.2.23 of this library is using github recommendations to communicate?

github article: https://github.blog/2021-09-01-improving-git-protocol-security-github/#libgit2-and-other-git-clients

**Comment by yodaldevoid** [comment]
The currently bundled version of `libssh2-sys` supports RSA-SHA2 with both the OpenSSL and mbedtls backends. There is also code upstream to support it on WinCNG.

I will look at updating our bundled version of `libssh2` to include the WinCNG support. Until then, I would follow the advice you were given at https://github.com/rust-lang/git2-rs/issues/872 and use the `openssl-on-win32` feature.
