### ISSUE TITLE
ssh2 libc dependency conflict

### ISSUE THREAD

**Issue by willem66745** [alexcrichton/ssh2-rs#27]
Currently I experience a build error when using the ssh2 crate from crates.io:

         Compiling ssh2 v0.2.9
      C:/msys/home/willem/.multirust/toolchains/stable/cargo\registry\src\github.com-0a35038f75765ae4\ssh2-0.2.9\src\channel.rs:225:49: 225:55 error: mismatched types:
       expected `u64`,
          found `usize`
      (expected u64,
          found usize) [E0308]
      C:/msys/home/willem/.multirust/toolchains/stable/cargo\registry\src\github.com-0a35038f75765ae4\ssh2-0.2.9\src\channel.rs:225                 exit_signal: convert(self, sig, siglen),

I guess this is related to the 0.1 dependency to libc when ssh2 v0.2.9 was created, and the libc 0.2 dependency the libssh2-sys crate has. When I directly use the *master* branch of the ssh2 crate, where the libc dependency is set to 0.2, no compilation errors do occur.

**Comment by alexcrichton** [comment]
Aha right I just pushed ssh2 0.2.10 which should fix the problem!
