### ISSUE TITLE
Publish libssh2-sys 0.3.0

### ISSUE THREAD

**Issue by luqmana** [alexcrichton/ssh2-rs#278]
Hi, could a new release for `libssh2-sys` be published (0.3.0) to crates.io. Looks like upstream libssh2 changes were pulled in that fix a number of issues (specifically getting the sha2 signature algorithm support).

Can confirm that pointing git2-rs at current master works to fetch from github with an rsa key whereas the latest version on crates.io (0.2.23) doesn't.

cc @yodaldevoid

**Comment by yodaldevoid** [comment]
Sadly I can't actually publish `libssh2-sys` so I will need to pass the buck on this one. That said, I agree that we should make another release of `libssh2-sys`.

@wez @crisidev

**Comment by wez** [comment]
@yodaldevoid I sent you an invite to be an owner for libssh2-sys

**Comment by lu-zero** [comment]
Would be possible to also publish a version that is compatible with the ssh2-rs used by cargo? I'm having lots of annoying problems due openwrt providing a too new libressl and a too stale glibc.

https://github.com/openwrt/packages/pull/19863

**Comment by yodaldevoid** [comment]
`ssh2` 0.9.4 and `libssh2-sys` 0.3.0 have both been published.
