### ISSUE TITLE
Support Rustls?

### ISSUE THREAD

**Issue by 0cv** [alexcrichton/ssh2-rs#280]
Are there plans to support Rustls instead of (or additionally to) openssl? The biggest advantage I'd see is for cross compilation, such as developing on Windows or Mac and deploy to Lambda. This requires at the moment to compile through e.g. Docker, as far as I could see.

**Comment by yodaldevoid** [comment]
That is a question for [`libssh2`](https://github.com/libssh2/libssh2). I'm fairly certain we can't add support for it unless they do.
