### ISSUE TITLE
Raw handles are not Send for multi-threaded listening.

### ISSUE THREAD

**Issue by chaaz** [alexcrichton/ssh2-rs#29]
When trying to handle multiple forward_listen requests on different threads, the following fails:

    let (mut listener, _) = session.channel_forward_listen(port, None, None).unwrap();
    loop {
      let channel = listener.accept().unwrap();
      thread::spawn(move || {
        let mut s = String::new();
        channel.read_to_string(&mut s).unwrap();
        println!("data: {}", s);
        println!("status: {}", channel.exit_status().unwrap());
      });
    }
  
with the errors:

    src/main.rs:22:5: 22:18 error: the trait `core::marker::Send` is not implemented for the type `*mut libssh2_sys::LIBSSH2_CHANNEL` [E0277]
    src/main.rs:22     thread::spawn(move || {
                       ^~~~~~~~~~~~~
    src/main.rs:22:5: 22:18 help: run `rustc --explain E0277` to see a detailed explanation
    src/main.rs:22:5: 22:18 note: `*mut libssh2_sys::LIBSSH2_CHANNEL` cannot be sent between threads safely
    src/main.rs:22:5: 22:18 note: required because it appears within the type `ssh2::channel::Channel<'_>`
    src/main.rs:22:5: 22:18 note: required because it appears within the type `[closure@src/main.rs:22:19: 27:6 channel:ssh2::channel::Channel<'_>]`
    src/main.rs:22:5: 22:18 note: required by `std::thread::spawn`
    src/main.rs:22:5: 22:18 error: the trait `core::marker::Sync` is not implemented for the type `*mut libssh2_sys::LIBSSH2_SESSION` [E0277]
    src/main.rs:22     thread::spawn(move || {
                       ^~~~~~~~~~~~~
    src/main.rs:22:5: 22:18 help: run `rustc --explain E0277` to see a detailed explanation
    src/main.rs:22:5: 22:18 note: `*mut libssh2_sys::LIBSSH2_SESSION` cannot be shared between threads safely
    src/main.rs:22:5: 22:18 note: required because it appears within the type `ssh2::session::Session`
    src/main.rs:22:5: 22:18 note: required because it appears within the type `ssh2::channel::Channel<'_>`
    src/main.rs:22:5: 22:18 note: required because it appears within the type `[closure@src/main.rs:22:19: 27:6 channel:ssh2::channel::Channel<'_>]`
    src/main.rs:22:5: 22:18 note: required by `std::thread::spawn`

`libssh2` claims to be thread-safe so long as its handles are not simultaneously shared. It would be great if the Rust library could reflect this.

**Comment by alexcrichton** [comment]
This is actually intentional, unfortunately. The unit of thread-safety in libssh2 is the `Session`, but you can't actually parallelize operations within a `Session` itself. For example you can't concurrently read/write two separate channels in the same session. This limitation is imposed by libssh2 itself.

Separate `Session` types are safe to use concurrently, however!

**Comment by alexcrichton** [comment]
@anacrolix yes in theory do do simultaneous reads/writes you'd need to use async I/O, although I don't think that'd be too easy to do with this library as-is (but in theory possible?)

**Comment by anacrolix** [comment]
I don't think it's possible, I get "would block" errors trying to use the channel if I put the session into nonblocking mode, and it just flat out hangs if I try to use it from tokio without nonblocking. I mentioned the details and some code in https://gitter.im/tokio-rs/tokio. Is there something that needs to change in ssh2 to make this work as expected?

Here's the code I'm working with, it should be runnable as is, and testable by tweaking the handful of address strings. https://gist.github.com/anacrolix/003a586f1f47f417813291f6b6e64207

**Comment by alexcrichton** [comment]
Yeah that's the "I don't think that'd be too easy to do with this library as-is", it's up to you to write all the code to handle all the would block errors.
