### ISSUE TITLE
Can't directly read/write to channel

### ISSUE THREAD

**Issue by k86td** [alexcrichton/ssh2-rs#292]
Hi! I'm getting started in a project where I'll need to run a SSH session to a remote device, run (mutliple) commands and get the output. However, with the code I've tried, I'm not capable of bidirectional interaction with the channel. Using `exec` works, but the context of the channel is not kept, which is a problem.

I'm currently testing with the following code:
```rust
use ssh2::Session;
use std::{net::TcpStream, io::{Write, Read}, str::from_utf8};

fn main() {
    let tcp = TcpStream::connect("redacted").unwrap();
    let mut ssh = Session::new().unwrap();
    let mut buf: Vec<u8> = Vec::new();

    ssh.set_tcp_stream(tcp);
    ssh.handshake().expect("can do the handshake");

    ssh.userauth_password("redacted", "redacted").unwrap();

    assert!(ssh.authenticated());
    println!("Authenticated!");

    let mut channel = ssh.channel_session().unwrap();
    println!("Opened channel");

    channel.request_pty("ansi", None, Some((500, 500, 500, 500))).unwrap();
    println!("Requested PTY");

    channel.shell().unwrap();
    println!("Requested SHELL");
    
    println!("Session blocking: {}", ssh.is_blocking());
    println!("Blocking directions: {:?}", ssh.block_directions());

    channel.write_all(b"cd /").unwrap();
    channel.write_all(b"ls -la").unwrap();

    println!("Starting to read...");
    channel.read_to_end(&mut buf).unwrap();
    print!("{}", from_utf8(&buf).unwrap());
    println!("Finished reading!");

    println!("Done, closing connections...");
    ssh.disconnect(None, "Closing connection", None).unwrap();
}
```

I can run it, but it hangs, the output:
```
❯ cargo run
   Compiling switchy v0.1.0
    Finished dev [unoptimized + debuginfo] target(s) in 0.64s
     Running `target\debug\switchy.exe`
Authenticated!
Opened channel
Requested PTY
Requested SHELL
Session blocking: true
Blocking directions: None
Starting to read...
```

I'm obligated to enter CTRL+C to exit. I find interesting that there are no blocking directions when the channel is opened. It's probably my fault and a missing step, but any help would be greatly appreciated. I will continue to do testing, and I'll update this if I find something.

Thank you.

**Comment by k86td** [comment]
So I dug back into this problem, and apparently you *could* manually set EOF, see [here](https://stackoverflow.com/questions/3083238/libssh2-channel-close-will-be-blocked-until-the-remote-command-exit).
However, I also found [this](https://github.com/libssh2/libssh2/issues/105) and [this](https://github.com/portnov/libssh2-hs/issues/71), and it seems there are very long archaic issues with Libssh2 (maybe).

 So I think the best bet would be to use a library like [thrussh](https://docs.rs/thrussh/latest/thrussh/), which doesn't seem to have any issues. I don't know if I should close this, I might try to make EOF work at some point and document my findings here.

**Comment by yodaldevoid** [comment]
Thank you for looking into this on your own. Looking into things on my own, and based on your references, your code is working as expected.

If you want non-blocking or async behavior I would suggest using `Session::set_blocking` or using `thrussh`, as you already found.

I'm going to close this for now, but feel free to continue recording your findings here for others if you feel like it.
