### ISSUE TITLE
Consider modifying parameters for this method : channel::request_pty_size()

### ISSUE THREAD

**Issue by JiKai126** [alexcrichton/ssh2-rs#304]
This is the current version:
```rust 
pub fn request_pty_size(
        &mut self,
        width: u32,
        height: u32,
        width_px: Option<u32>,
        height_px: Option<u32>,
    ) -> Result<(), Error> 
```
I would like to modify this code to look like the following:
```rust
pub fn request_pty_size<W>(
        &mut W,
        width: u32,
        height: u32,
        width_px: Option<u32>,
        height_px: Option<u32>,
    )  
where
    W: Write
 ```
Because I'm using `fn split(self) -> (ReadHalf<Self>, WriteHalf<Self>)`,I can not to use `request_pty_size`

**Comment by yodaldevoid** [comment]
I'm not sure how your suggested code would work. Beyond that, I cannot find a `split` method or function in `ssh2` or `ReadHalf` or `WriteHalf` structures. Perhaps you are mixing up code from this library and another?

**Comment by JiKai126** [comment]
I'm sorry, this issue shouldn't be related to this library.
