### ISSUE TITLE
Update dependency `bitflags` to v2?

### ISSUE THREAD

**Issue by LeoniePhiline** [alexcrichton/ssh2-rs#307]
`bitflags` v2 became available in March 2023: https://crates.io/crates/bitflags/versions 

Major changes: https://github.com/bitflags/bitflags/releases/tag/2.0.0

Since an `ssh2` release is outstanding, this might be a good opportunity for possibly breaking public changes.

**Comment by yodaldevoid** [comment]
Closed by https://github.com/alexcrichton/ssh2-rs/pull/308
