### ISSUE TITLE
Non standard SSH agent is not working

### ISSUE THREAD

**Issue by braden-godley** [alexcrichton/ssh2-rs#316]
I have configured my `~/.ssh/config` to use the 1Password SSH agent. However, it seems that this doesn't work with libssh2, as I found out in an issue while using gitui: https://github.com/extrawurst/gitui/issues/2216

Is this something that should be fixed with this package? I saw #211 but I wasn't sure (i am a noob) if the conclusion was that libssh2 just doesn't deal with `~/.ssh/config`

If this is indeed within the scope of this package, I'd be really happy to see it fixed!

**Comment by yodaldevoid** [comment]
As stated in #211, `~/.ssh/config` is not read by `libssh2` (the C library that this Rust library/crate wraps around). If you would like to see this feature added, you will need to take it up with the maintainers of `libssh2`.
