### ISSUE TITLE
keyboard-interactive authentication panics - with a potential fix

### ISSUE THREAD

**Issue by ayourtch** [alexcrichton/ssh2-rs#318]
The handler for keyboard-interactive uses from_raw_parts(), and several fields get null pointer and zero length passed, which results in panics.

I have fixed it in my own fork here - https://github.com/alexcrichton/ssh2-rs/compare/master...ayourtch:ssh2-rs:fix-interactive-auth - is it something that you would entertain having me open a PR for ? Anything that I should update ? 

(I was thinking running cargo fmt, but from experience, it sometimes behaves slightly differently depending on the version, so I deliberately avoided it).

Thanks!

**Comment by yodaldevoid** [comment]
Fixed by #333
