### ISSUE TITLE
Panic when channel belonging to non-blocking session is dropped

### ISSUE THREAD

**Issue by davidsm** [alexcrichton/ssh2-rs#32]
`libssh2_channel_free` might return -37 (EAGAIN) for a non-blocking session, which causes the assertion in Channel#drop to fail 
```rust
assert_eq!(raw::libssh2_session_free(self.raw), 0);
```
While -37 is an error code, it does not really represent an error in this case.

Can be worked around by simply setting the session to blocking again, just before it goes out of scope.

Code sample to reproduce the issue:
```rust
    let tcp = TcpStream::connect(REMOTE_HOST)
        .expect("Could not connect to server");
    {
        let mut sess = Session::new().expect("Could not open session");
        sess.handshake(&tcp).expect("Could not complete handshake");

        sess.userauth_pubkey_file(REMOTE_USER, None, Path::new(PUBKEY_PATH), None)
            .expect("Could not authenticate");

        let mut channel = sess.channel_direct_tcpip(FORWARD_HOST_ADDR,
                                                    FORWARD_HOST_PORT,
                                                    None)
            .expect("Could not make direct TCP/IP connection");
        sess.set_blocking(false);
    }
```

**Comment by alexcrichton** [comment]
Thanks for the report! I removed the assertion in https://github.com/alexcrichton/ssh2-rs/commit/ef90d566f010d9fd997ccd2d0c68081efd26db32, but unfortunately that basically means the session will be leaked. I'd probably recommend making sure everything is shut down before dropping, but it at least shouldn't panic now!

**Comment by davidsm** [comment]
My apologies, I was initially wrong on where the assertion failed. I edited the report, but I guess you might have seen it before that (and I see now that I missed updating the code quote). The assertion fails in channel.rs, not in session.rs (though it can perhaps fail there too if drop for channel hadn't panicked).

**Comment by alexcrichton** [comment]
Ah ok, no worries! I just pushed a commit which ignores the return value in `Channel::drop` as well
