### ISSUE TITLE
[rfe] Mimic default ssh functionality

### ISSUE THREAD

**Issue by erpadmin** [alexcrichton/ssh2-rs#331]
Cli ssh attempts keyauth with a default list ~/.ssh/id_dsa, ~/.ssh/id_ecdsa, ~/.ssh/id_ed25519 and ~/.ssh/id_rsa.

The ask here is for an auth function that attempts this as current user and/or by specifying only user.

**Comment by yodaldevoid** [comment]
This is not something for this library to implement as we don't want to implicitly load key files as that may be a security issue. This should be implemented by the user of this library.
