### ISSUE TITLE
A read limit of 0 should not imply eof

### ISSUE THREAD

**Issue by aidanhs** [alexcrichton/ssh2-rs#34]
Consider
```
extern crate ssh2;

fn main() {
        use std::io::prelude::*;
        use std::net::TcpStream;
        use ssh2::Session;

        let tcp = TcpStream::connect("127.0.0.1:22").unwrap();
        let mut sess = Session::new().unwrap();
        sess.handshake(&tcp).unwrap();
        sess.userauth_password("aidanhs", "password").unwrap();
        assert!(sess.authenticated());

        let mut channel = sess.channel_session().unwrap();
        channel.limit_read(0);
        channel.exec("sleep 1; ls").unwrap();
        let mut s = String::new();
        channel.read_to_string(&mut s).unwrap();
        println!("{}", s);
        println!("{}", channel.exit_status().unwrap());
        channel.send_eof().unwrap();
        channel.wait_eof().unwrap();
        channel.close().unwrap();
        println!("eof: {}", channel.eof());
        channel.wait_close().unwrap();

}
```
Output:
```
 $ cargo run
   Compiling test v0.1.0 (file:///home/aidanhs/Desktop/hadean/test)
     Running `target/debug/test`

0
eof: true
thread '<main>' panicked at 'called `Result::unwrap()` on an `Err` value: Error { code: -34, msg: "libssh2_channel_wait_closed() invoked when channel is not in EOF state" }', ../src/libcore/result.rs:746
note: Run with `RUST_BACKTRACE=1` for a backtrace.
Process didn't exit successfully: `target/debug/test` (exit code: 101)
```

There are a couple of things worth noting here:

1. The important one, `eof()` returns true but `wait_close()` complains it's not eof. I've looked at the code and I'm not sure what the correct solution here is, but the current behaviour feels subideal. Comment out `limit_read()` to make it work.
2. `exit_status()` returned 0 even though the command hadn't finished - it should probably be documented that a return code of 0 may mean success or an unfinished process.

**Comment by alexcrichton** [comment]
Oh gah the `limit_read` function isn't really intended to be used publicly, it's [just a hack](https://github.com/alexcrichton/ssh2-rs/blob/9eb9a5b85c359e1ee8aa8016eecb516039bf4069/src/session.rs#L432-L437) to work around weird behavior in `scp_recv`. I suspect that it may be more prudent to fix the underlying bug, however?

**Comment by alexcrichton** [comment]
Ah yeah it looks like in the libssh2 examples you have to just read up to the size listed in the stat returned, rather than testing for `eof` and returning after that...

If you avoid the `limit_read` API, does it work out otherwise? I may try to remove that or hide it and document it as a hack.

**Comment by aidanhs** [comment]
Yeah it's fine without `limit_read`. I assume you'll just make it private?

In other news, `wait_eof` appears to be documented very misleadingly in libssh2 - http://www.libssh2.org/libssh2_channel_wait_eof.html (and therefore in this library).
Although it says "Wait for the remote end to acknowledge an EOF request", which (to my reading) means the remote end is saying "yes, I got your `send_eof`". However:

 - it waits for `remote.eof` in https://github.com/libssh2/libssh2/blob/d441da3086dcc49989b7c5b9bf3043c4a6a98211/src/channel.c#L2233
 - `remote.eof` is set in response to a `SSH_MSG_CHANNEL_EOF` message https://github.com/libssh2/libssh2/blob/d441da3086dcc49989b7c5b9bf3043c4a6a98211/src/packet.c#L744
 - "When a party will no longer send more data to a channel, it SHOULD send SSH_MSG_CHANNEL_EOF." per section 5.3/page 8 of https://www.ietf.org/rfc/rfc4254.txt

So what it actually means is "wait for the remote end to have nothing more to send", which sounds a bit different!

**Comment by alexcrichton** [comment]
Thanks for checking! I think yeah I'll try to make it private and not exposed at all (or at least `doc(hidden)` and documented as deprecated for now).

Want to make a PR for the doc fixes though?

**Comment by aidanhs** [comment]
I think I'll try and get the doc fixes upstream.
