### ISSUE TITLE
build calls `make` instead of `$MAKE` with `$MAKEFLAGS`

### ISSUE THREAD

**Issue by rkitover** [alexcrichton/ssh2-rs#39]
Hi,

on openbsd `make` is bsd make and `gmake` is GNU make. If gmake is used to build a cargo project, as is generally required, then it sets `$MAKEFLAGS` specific to gmake which the bsd make does not understand, but when this crate builds it calls `make` instead of `$MAKE` (which would be gmake) and my build fails with this:

```
make: illegal argument to -j option -- --jobserver-fds=3,4 -- not a number
usage: make [-BeiknpqrSst] [-C directory] [-D variable] [-d flags] [-f mk]
            [-I directory] [-j max_processes] [-m directory] [-V variable]
            [NAME=value] [target ...]
thread '<main>' panicked at '
command did not execute successfully, got: exit code: 2
```

This is with libssh2-sys v0.1.36 while building cargo 0.9.0.

**Comment by alexcrichton** [comment]
This actually just uses `cmake` to build, so perhaps there's a buggy cmake on the system?

**Comment by rkitover** [comment]
Thanks, I'll see if I can patch the OpenBSD cmake to fix this.
