### ISSUE TITLE
diffie-hellman-group-exchange-sha256 not supported

### ISSUE THREAD

**Issue by maximih** [alexcrichton/ssh2-rs#44]
Hi

I am trying to connect to a server which is only allowing `diffie-hellman-group-exchange-sha256` as key exchange protocol but the `libssh2` version used by `ssh2-rs` does not seem to have support for `diffie-hellman-group-exchange-sha256`. 

Can you update the `libssh2` commit hash to point to a version which has support for `diffie-hellman-group-exchange-sha256`? 

Thanks

**Comment by alexcrichton** [comment]
Done! (updated to the current master)
