### ISSUE TITLE
Issues with ssh session to network gear.

### ISSUE THREAD

**Issue by MrSpock** [alexcrichton/ssh2-rs#48]
I stuck upon problem with using this create when connecting to network gear instead of for example Linux server.
Following code works perfectly when host is Linux box but fail if its for example cisco switch:

```
                match channel {
                    Ok(mut c) => {
                        println!("Channel acquired !");
                        c.exec(cmd).expect("Channel error: ");
                        println!("Command executed !");
                        let mut s = String::new();
                        c.read_to_string(&mut s).unwrap();
                        s
                        // String::from("test")
                    }
                    Err(e) => {
                        println!("Something was WTF ..!");
                        String::from("")
                    }
                }
```

When running against cisco switch I'm getting following error:

```
Requesting channel ..
Channel acquired !
thread 'main' panicked at 'Channel error: : Error { code: -43, msg: "Failed waiting for channel success" }', ../src/libcore/result.rs:788
```

I'm suspecting that  before exec I need to create shell or request pty. 
Is there some example how to work with channel.shel()l and pty's   not directly calling exec() ?

**Comment by alexcrichton** [comment]
Interesting! I'm not personally too privy to the details of the ssh protocol, but perhaps you could try allocating a shell/pty and see if it works in both places? I guess there can be daemon specific behavior depending on what the backing daemon is.

**Comment by MrSpock** [comment]
I'm sorry but I'm not fluent in ssh details to :) Can you provide simple rust  example how to allocate shell/pty _before_ calling exec or as a replacement ?

**Comment by alexcrichton** [comment]
Heh, maybe! Perhaps calling [`shell`](http://alexcrichton.com/ssh2-rs/ssh2/struct.Channel.html#method.shell) ahead of time before `exec`? Maybe [`request_pty`](http://alexcrichton.com/ssh2-rs/ssh2/struct.Channel.html#method.request_pty) as well? I'd probably just play around with various methods on `Channel` to see what works.
