### ISSUE TITLE
0.2.14 has breaking change

### ISSUE THREAD

**Issue by e-oz** [alexcrichton/ssh2-rs#49]
After release of ssh2 0.2.14 each my "cargo build" fails with error:

```
 Updating registry `https://github.com/rust-lang/crates.io-index`
error: native library `openssl` is being linked to by more than one version of the same package, but it can only be linked once; try updating or pinning your dependencies to ensure that this package only shows up once

  openssl-sys v0.7.17
  openssl-sys v0.9.0
```

After that I have to manually edit Cargo.lock to revert changes in dependencies back.

I understand my problem is a drop in the sea and generally it's not the problem of this crate, but could you please version it not as third number change (minor), to don't let Cargo automatically update dependency to next version? 

Dependencies are declared explicitly, without "~" or "^", but Cargo is trying to update version anyway:

ssh2 = "0.2.13"
openssl = "0.7.14"
openssl-sys = "0.7.17"
libssh2-sys = "0.1.39"

**Comment by alexcrichton** [comment]
Yes unfortunately the sys rule here means that it's difficult to upgrade crates in minor versions across those boundaries, but there were no API breaking changes is is sort of what I was communicating with the lack of a major version bump (seems a bummer for a minor update like this). Is it possible to locally either use a lock file or upgrade to openssl-sys 0.9?

**Comment by e-oz** [comment]
Well, when crate can't be compiled it's sort of breaking change, even if API is the same :)
Lock file only can be used for dependencies of my crate, but not for crates it uses as dependencies. In other words, I can't ask Hyper or Iron to upgrade their dependency. So right now I have to vendor them.

**Comment by alexcrichton** [comment]
Unfortunately I think this may just be the reality of bumping widely-used `*-sys` dependencies right now. The 0.2.14 didn't actually have a breaking change in the sense that 0.2.13 was broken in the face of the `openssl-sys` upgrade just as 0.2.14 can be considered right now. In that sense the publish of 0.9 of openssl-sys broke this no matter what, and that's what lock files are intended to accomplish (locking down the dependency graph)

**Comment by alexcrichton** [comment]
Ok, I believe I've fixed this now
