### ISSUE TITLE
LIBSSH_CHANNEL being freed more than once?

### ISSUE THREAD

**Issue by steveatinfincia** [alexcrichton/ssh2-rs#50]
Getting this while calling scp commands, on the surface it doesn't *appear* I'm doing something obviously wrong, but I'm not sure.

A very quick read of `ssh2` and `libssh2` itself show that these `LIBSSH2_CHANNEL`s can potentially be passed to `libssh2_channel_free()` in more than one place like this: 

1) `libssh2` itself calls `libssh2_channel_free()` on the the `LIBSSH2_CHANNEL`, which happens quite a few places including inside [scp_send](https://github.com/libssh2/libssh2/blob/64ebfd8182a9b6e637e65c3059e3798e199274b3/src/scp.c#L1088)'s error handler
2) then `Channel` is [dropped in Rust](https://github.com/alexcrichton/ssh2-rs/blob/master/src/channel.rs#L375), which also calls `libssh2_channel_free()`

I started adding code to call `libssh2_trace()` before running any commands to see *why* it was trying to free that channel inside libssh2 itself, assuming that's what's actually happening, but from outside of `libssh2-sys` the `raw` field in `Session` is private, so can't be passed as an argument in user code. It might be smart to add a way to trigger that from inside `ssh2`.

Thanks to anyone who has any ideas :)

    test(54200,0x7fffe87de3c0) malloc: *** error for object 0x100d000f0: pointer being freed was not allocated
    *** set a breakpoint in malloc_error_break to debug
    Process 54200 stopped
    * thread #1: tid = 0x45e2129, 0x00007fffdfc50147 libsystem_malloc.dylib`malloc_error_break, queue = 'com.apple.main-thread', stop reason = breakpoint 1.1
    frame #0: 0x00007fffdfc50147 libsystem_malloc.dylib`malloc_error_break
    libsystem_malloc.dylib`malloc_error_break:
    ->  0x7fffdfc50147 <+0>: pushq  %rbp
    0x7fffdfc50148 <+1>: movq   %rsp, %rbp
    0x7fffdfc5014b <+4>: nop    
    0x7fffdfc5014c <+5>: nopl   (%rax)
    (lldb) bt
    * thread #1: tid = 0x45e2129, 0x00007fffdfc50147 libsystem_malloc.dylib`malloc_error_break, queue = 'com.apple.main-thread', stop reason = breakpoint 1.1
    * frame #0: 0x00007fffdfc50147 libsystem_malloc.dylib`malloc_error_break
    frame #1: 0x00007fffdfc4201e libsystem_malloc.dylib`free + 409
    frame #2: 0x0000000100122179 test`libssh2_default_free + 25
    frame #3: 0x000000010010f35c test`_libssh2_channel_free + 476
    frame #4: 0x0000000100112c9e test`libssh2_channel_free + 62
    frame #5: 0x00000001001218d0 test`scp_send + 2832
    frame #6: 0x0000000100121978 test`libssh2_scp_send64 + 72
    frame #7: 0x0000000100174d16 test`ssh2::session::{{impl}}::scp_send(self=0x00007fff5fbff718, remote_path=0x0000000100b02540, mode=420, size=1081, times=Option<(u64, u64)> @ 0x00007fff5fbf7930) + 1254 at session.rs:456
    frame #8: 0x000000010015dc2e test`sdsync::add_block(db=0x00007fff5fbff808, ssh_session=0x00007fff5fbff718, unique_client_id=(data_ptr = "12345", length = 5), hmac=(data_ptr = "л?Zy?\x82\x8cW⢝\x80Tա?q-\x95??6?m?Id??\a63d6ff853569a0aadec5f247bba51786H??_?, length = 32), key=(data_ptr = "??h\x9d\tA?G?J?k\x99??3?\x1f\x85{???1U???\U00000087?E\x8b HZl??\x806\vC?{\x8c\x85?難\x1e`\x82GA#\x84}3Mz\x9b.??????y\x86?7??&\x9e????\thV!??7\x13?m?\x85#???3a??\"?ȴO?\v?\x87?8R\x1e??̝\x8c*\x96&\x97^\x8f))A????/\x8a?\x06a??A8-i)?\x0e???Z??????\x1c?*?@??E??@K?q~\x89???o?bB??A?e\x95m??\v\x11?\x12?k?(", length = 48), chunk_data=(data_ptr = "?5?HA9?0G?J\x1a?}?\f6??x.\x9d??\x90??u݂\x9c?	R\x8d\x82?5?w??~?01?3\n?o?S\x8c\x8c\x8c?7?JHU??*\x04?J/{?!?1?\\?c?0AVh??:?¸\x01#?e?\"x\x02\x0eM\x1c?@???Q?#\fS??t?Q\x14U?(???f\x89I7???\x91?Y\x15?܎\x97?E&c\x9e\x16?B?\tԤET\bK?Z?C???)\x95F?????BPTL7b,\x1a?i9?\x15??8??/?J\x93*m??=\x92\x8cB\x0e\x1c6?Li?G?\x9a?1?y\x93?\x9c\x80?M?3N\x19??,f\x865}??#j&rG1????\x11??\x1a??^?<_????S\x9e?T\x98s#??ݭ\"\x9e???iE\x19\U0000009b\x87s]\x90?65?kqQ?\x19B0?g\x9c?7?\x82ѻ\x8b0\x03?@?{V?3Il?j?`*??s?Q?\x17~\x80?\x11X?\x1ak\x03?P\bأy?\x11_?2\x1b??p&?}i?I@O?,?/Td???=\x9b????\x9b?}b4M\\?\x8d?Z\x91????XJj4lu\x1b??\x9c\x01\x90?DȔ??\x85\x15\ba??\x82G?xԹ\f\x19?t??\x18\x0f!\x12??S?>\x84?B\x91ȸ\x88F1\x89d\x7fd:C\x86)?g??d\x13\x81?zA?Mh\x059\x97?OE\x84>xY?A\x16[\x19A?&ԑ̂V??Y0\x86\x80??H2)V\x81\x87?=???Wb0\x0fz\x16e_OI?_??\x0e\x18A????\x9b?p0\x06s\x13[\x12hh&??2??m+9??\n̽\x129B^j\x80\x1b?(?\x04A\x98&\x1e'\x86)?E1L?<??\v?d??!6\x88?]?L?x??ftN??治?>h??\x99^RZ+?9??SS???\x7fA?p/?\x12?ר?H?\x0eG\t?Z\x7fc^???ۍ??????X\x8eR??:?\???\x7f\"ws\x86?q????|+\x1c\x97}??T\x8d\x02\x83L??\\C??:???\f??\x88w??r&\bc\"Q_?fn Al??~a?9v\x15?g\x86?Gp\x91KPM\x1a0]?c\x98z?I?N\U0000001d\x8a\x83?x.?#A?, length = 1033)) + 1262 at lib.rs:952
    frame #9: 0x000000010015a58e test`sdsync::sdsync_create_archive(context=0x0000000100d00000, folder_id=1) + 7086 at lib.rs:559
    frame #10: 0x0000000100001149 test`main + 297
    frame #11: 0x00007fffdfabe255 libdyld.dylib`start + 1

Snippet of the setup code being used:

    let tcp = TcpStream::connect((ip, port)).unwrap();
    let mut ssh_session = Session::new().unwrap();

    ssh_session.handshake(&tcp).unwrap();
    ssh_session.userauth_password(ssh_username, ssh_password).unwrap();
    assert!(ssh_session.authenticated());

Then the `Session` is passed to another function so this is called repeatedly:

    let mut to_write = Vec::new();
    to_write.extend(data);
    let mut chunk_path = Path::new("/storage/").to_owned();
    let mut remote_file = ssh_session.scp_send(&chunk_path, 0o644, to_write.len() as u64, None).unwrap();
    remote_file.write(&to_write).unwrap();

**Comment by alexcrichton** [comment]
Hm here that channel never made its way out into Rust, so I don't think we're freeing it in Rust and then it's being freed again in libssh2?

You wouldn't happen to have a relatively self-contained example, would you? I may be able to help debug locally if so.

**Comment by steveatinfincia** [comment]
You're right that shouldn't actually be the case here.

Ok, I think I will pull some of that code out into a separate rust lib for testing purposes & see what I can find, will upload if it's reproducible separately :)

Thanks!

**Comment by steveatinfincia** [comment]
Ok so I was able to replicate this *and* get it to work as-is using sftp calls instead, so it would appear the libssh2 library is working normally here in general (wanted to rule out freak compiler accidents :P ).

I'm still not 100% sure I didn't break something *somehow*, but in my test code there are no unsafe blocks (unlike the code it was pulled from).

This has 2 alternate paths that, as far as I know, should be roughly the same. One using scp calls the other sftp. Each uses some static fake data to upload, concatenating it 100 times to approximate an ~80k file.

It also runs multiple uploads using the same ssh session, when I only do it once here it didn't trigger the segfault, but the 2nd time always does with the scp version.

https://gist.github.com/steveatinfincia/342f2e3e6362e69899e138d79aade55a

**Comment by alexcrichton** [comment]
Weird! I couldn't reproduce on either Linux or OSX though, unfortunately. I wonder if it's a bug in libssh2 about some remote server weirdness?

**Comment by steveatinfincia** [comment]
Hi again, and sorry for the delay in getting back around to this :)

I can't explain it either at this point. It's got to be either something down in libssh2 itself (perhaps only in the binary that gets compiled here, or related to the server interaction somehow), or something strange going on with this system.

Either way it's clearly not ssh2-rs, which is excellent. 

Thanks :)
