### ISSUE TITLE
Interrupt a spawned remote application

### ISSUE THREAD

**Issue by dzobbe** [alexcrichton/ssh2-rs#52]
Hi Alex, Hi All,

Did you implemented something able to interrupt the execution of a spawned remote application. I am interested in launching a server remotely and after a while interrupt it and launch it again. However, I am currently stucked because the process keeps running. 

I am able to do it through bash through the -t option: 
`ssh  -t [user]@[host]  '[somepath]/bin/memcached -l 127.0.0.1 -p 1245 -vv'  `

Can you help me with the rust APIs?
Thanks

**Comment by dzobbe** [comment]
Looking around I have found this function in libssh2 APIs, which should fit for my case:
`ssh_channel_request_send_signal()`

With this one I should be able to launch a SIGHUP to interrupt the application.
I checked out in the rust lib but I did not found something like that. Am I correct?

**Comment by alexcrichton** [comment]
I think that API may be from another library? (perhaps libssh?)

It may be the case that libssh2 doesn't have this implemented yet

**Comment by dzobbe** [comment]
Yeah you're right! I figured out by executing a pkill on the process spawned.

Thanks alex and congrats for your work in rust ;)
