### ISSUE TITLE
Could NOT find ZLIB

### ISSUE THREAD

**Issue by Henning-K** [alexcrichton/ssh2-rs#56]
Hi! When I try to build cargo on Windows as a library for my program libssh2-rs fails to build with the following error:

toolchain: stable-x86_64-pc-windows-gnu
rustc-version: rustc 1.15.1 (021bd294c 2017-02-08)
OS: Windows 7 64bit
Msys64 installed

error: failed to run custom build command for `libssh2-sys v0.2.5`
process didn't exit successfully: `E:\development\cargo-authors\target\debug\build\libssh2-sys-04373e2a6b69259d\build-script-build` (exit code: 101)
--- stdout
running: "cmake" "C:\\Users\\***\\.cargo\\registry\\src\\github.com-1ecc6299db9ec823\\libssh2-sys-0.2.5\\libssh2" "-G" "MSYS Makefiles" "-DCRYPTO_BACKEND=WinCNG" "-DZLIB_INCLUDE_DIR=E:\\development\\cargo-authors\\target\\debug\\build\\libz-sys-c29f5c61ff9da9c5\\out/include" "-DBUILD_SHARED_LIBS=OFF" "-DENABLE_ZLIB_COMPRESSION=ON" "-DCMAKE_INSTALL_LIBDIR=lib" "-DBUILD_EXAMPLES=OFF" "-DBUILD_TESTING=OFF" "-DCMAKE_INSTALL_PREFIX=E:\\development\\cargo-authors\\target\\debug\\build\\libssh2-sys-9b7d67f8c921632b\\out" "-DCMAKE_C_FLAGS= -ffunction-sections -fdata-sections -m64" "-DCMAKE_CXX_FLAGS= -ffunction-sections -fdata-sections -m64" "-DCMAKE_BUILD_TYPE=Debug"
-- The C compiler identification is GNU 6.3.0
-- Check for working C compiler: C:/msys64/usr/bin/gcc.exe
-- Check for working C compiler: C:/msys64/usr/bin/gcc.exe -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Looking for include files windows.h, bcrypt.h
-- Looking for include files windows.h, bcrypt.h - found
-- Looking for include file ntdef.h
-- Looking for include file ntdef.h - found
-- Looking for include file ntstatus.h
-- Looking for include file ntstatus.h - found
-- Looking for include files windows.h, wincrypt.h
-- Looking for include files windows.h, wincrypt.h - found
-- Configuring incomplete, errors occurred!
See also "E:/Development/cargo-authors/target/debug/build/libssh2-sys-9b7d67f8c921632b/out/build/CMakeFiles/CMakeOutput.
log".

--- stderr
fatal: Not a git repository (or any of the parent directories): .git
CMake Error at C:/Program Files/CMake/share/cmake-3.7/Modules/FindPackageHandleStandardArgs.cmake:138 (message):
  Could NOT find ZLIB (missing: ZLIB_LIBRARY) (found version "1.2.8")
Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.7/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  C:/Program Files/CMake/share/cmake-3.7/Modules/FindZLIB.cmake:114 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  src/CMakeLists.txt:239 (find_package)

thread 'main' panicked at '
command did not execute successfully, got: exit code: 1

build script failed, must exit now', C:\Users\***\.cargo\registry\src\github.com-1ecc6299db9ec823\cmake-0.1.20\src\lib.rs:573

**Comment by alexcrichton** [comment]
Could you provide a full build log which includes versions of dependencies used as well? This *may* have been fixed with a libz-sys update, but I forget at this point unfortunately :(

If you've got more info to debug with that'd also be super helpful. Unfortunately as-is there's not enough to go by for me to identify what's wrong :(

**Comment by Henning-K** [comment]
According to Cargo.lock:

[[package]]
name = "libssh2-sys"
version = "0.2.5"
source = "registry+https://github.com/rust-lang/crates.io-index"
dependencies = [
 "cmake 0.1.20 (registry+https://github.com/rust-lang/crates.io-index)",
 "libc 0.2.20 (registry+https://github.com/rust-lang/crates.io-index)",
 "libz-sys 1.0.12 (registry+https://github.com/rust-lang/crates.io-index)",
 "openssl-sys 0.9.6 (registry+https://github.com/rust-lang/crates.io-index)",
 "pkg-config 0.3.9 (registry+https://github.com/rust-lang/crates.io-index)",
]

[[package]]
name = "libz-sys"
version = "1.0.12"
source = "registry+https://github.com/rust-lang/crates.io-index"
dependencies = [
 "gcc 0.3.43 (registry+https://github.com/rust-lang/crates.io-index)",
 "libc 0.2.20 (registry+https://github.com/rust-lang/crates.io-index)",
 "pkg-config 0.3.9 (registry+https://github.com/rust-lang/crates.io-index)",
]

**Comment by Henning-K** [comment]
And the full build log:

   Compiling pkg-config v0.3.9
   Compiling crossbeam v0.2.10
   Compiling libc v0.2.20
   Compiling strsim v0.5.2
   Compiling log v0.3.6
   Compiling matches v0.1.4
   Compiling winapi-build v0.1.1
   Compiling rustc-demangle v0.1.4
   Compiling filetime v0.1.10
   Compiling num_cpus v1.2.1
   Compiling unicode-bidi v0.2.4
   Compiling utf8-ranges v0.1.3
   Compiling ws2_32-sys v0.2.1
   Compiling kernel32-sys v0.2.2
   Compiling advapi32-sys v0.2.0
   Compiling dbghelp-sys v0.2.0
   Compiling psapi-sys v0.1.0
   Compiling rustc-serialize v0.3.22
   Compiling backtrace v0.3.0
   Compiling unicode-normalization v0.1.4
   Compiling rand v0.3.15
   Compiling cfg-if v0.1.0
   Compiling memchr v0.1.11
   Compiling lazy_static v0.2.2
   Compiling glob v0.2.11
   Compiling bitflags v0.7.0
   Compiling gcc v0.3.43
   Compiling aho-corasick v0.5.3
   Compiling winapi v0.2.8
   Compiling tar v0.4.10
   Compiling idna v0.1.0
   Compiling regex-syntax v0.3.9
   Compiling tempdir v0.3.5
   Compiling backtrace-sys v0.1.10
   Compiling cmake v0.1.20
   Compiling libz-sys v1.0.12
   Compiling miniz-sys v0.1.9
   Compiling url v1.4.0
   Compiling curl-sys v0.3.8
   Compiling libssh2-sys v0.2.5
   Compiling libgit2-sys v0.6.6
   Compiling toml v0.2.1
   Compiling flate2 v0.2.17
Build failed, waiting for other jobs to finish...
error: failed to run custom build command for `libssh2-sys v0.2.5`
process didn't exit successfully: `E:\Development\cargo-authors\target\debug\build\libssh2-sys-04373e2a6b69259d\build-script-build` (exit code: 101)
--- stdout
running: "cmake" "C:\\Users\\***\\.cargo\\registry\\src\\github.com-1ecc6299db9ec823\\libssh2-sys-0.2.5\\libssh2" "-G" "MSYS Makefiles" "-DCRYPTO_BACKEND=WinCNG" "-DZLIB_INCLUDE_DIR=E:\\Development\\cargo-authors\\target\\debug\\build\\libz-sys-c29f5c61ff9da9c5\\out/include" "-DBUILD_SHARED_LIBS=OFF" "-DENABLE_ZLIB_COMPRESSION=ON" "-DCMAKE_INSTALL_LIBDIR=lib" "-DBUILD_EXAMPLES=OFF" "-DBUILD_TESTING=OFF" "-DCMAKE_INSTALL_PREFIX=E:\\Development\\cargo-authors\\target\\debug\\build\\libssh2-sys-9b7d67f8c921632b\\out" "-DCMAKE_C_FLAGS= -ffunction-sections -fdata-sections -m64" "-DCMAKE_CXX_FLAGS= -ffunction-sections -fdata-sections -m64" "-DCMAKE_BUILD_TYPE=Debug"
-- The C compiler identification is GNU 6.3.0
-- Check for working C compiler: C:/msys64/usr/bin/gcc.exe
-- Check for working C compiler: C:/msys64/usr/bin/gcc.exe -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Looking for include files windows.h, bcrypt.h
-- Looking for include files windows.h, bcrypt.h - found
-- Looking for include file ntdef.h
-- Looking for include file ntdef.h - found
-- Looking for include file ntstatus.h
-- Looking for include file ntstatus.h - found
-- Looking for include files windows.h, wincrypt.h
-- Looking for include files windows.h, wincrypt.h - found
-- Configuring incomplete, errors occurred!
See also "E:/Development/cargo-authors/target/debug/build/libssh2-sys-9b7d67f8c921632b/out/build/CMakeFiles/CMakeOutput.log".

--- stderr
fatal: Not a git repository (or any of the parent directories): .git
CMake Error at C:/Program Files/CMake/share/cmake-3.7/Modules/FindPackageHandleStandardArgs.cmake:138 (message):
  Could NOT find ZLIB (missing: ZLIB_LIBRARY) (found version "1.2.8")
Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.7/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  C:/Program Files/CMake/share/cmake-3.7/Modules/FindZLIB.cmake:114 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  src/CMakeLists.txt:239 (find_package)


thread 'main' panicked at '
command did not execute successfully, got: exit code: 1

build script failed, must exit now', C:\Users\***\.cargo\registry\src\github.com-1ecc6299db9ec823\cmake-0.1.20\src\lib.rs:573
note: Run with `RUST_BACKTRACE=1` for a backtrace.

**Comment by alexcrichton** [comment]
Could you try updating libz-sys to 1.0.13?

**Comment by Henning-K** [comment]
I actually have no idea why it doesn't do that automatically considering the semver requirement of libssh2-rs (>= 0) and me having used "cargo clean" already several times. Doesn't that do it? If not, what would I have to do? Maybe removing the Cargo.lock file?

**Comment by alexcrichton** [comment]
You can run `cargo update -p libz-sys` to update that dependency.

**Comment by Henning-K** [comment]
Also, I noticed that from the "build finished [...]" message on the console to completion it takes several minutes, might just be my PC though...

**Comment by Henning-K** [comment]
Still fails after updating libz-sys:

   Compiling pkg-config v0.3.9
   Compiling crossbeam v0.2.10
   Compiling libc v0.2.20
   Compiling strsim v0.5.2
   Compiling log v0.3.6
   Compiling matches v0.1.4
   Compiling winapi-build v0.1.1
   Compiling rustc-demangle v0.1.4
   Compiling filetime v0.1.10
   Compiling num_cpus v1.2.1
   Compiling unicode-bidi v0.2.4
   Compiling utf8-ranges v0.1.3
   Compiling ws2_32-sys v0.2.1
   Compiling kernel32-sys v0.2.2
   Compiling advapi32-sys v0.2.0
   Compiling dbghelp-sys v0.2.0
   Compiling psapi-sys v0.1.0
   Compiling rustc-serialize v0.3.22
   Compiling backtrace v0.3.0
   Compiling unicode-normalization v0.1.4
   Compiling rand v0.3.15
   Compiling cfg-if v0.1.0
   Compiling memchr v0.1.11
   Compiling lazy_static v0.2.2
   Compiling glob v0.2.11
   Compiling bitflags v0.7.0
   Compiling gcc v0.3.43
   Compiling aho-corasick v0.5.3
   Compiling winapi v0.2.8
   Compiling tar v0.4.10
   Compiling idna v0.1.0
   Compiling regex-syntax v0.3.9
   Compiling tempdir v0.3.5
   Compiling backtrace-sys v0.1.10
   Compiling cmake v0.1.20
   Compiling libz-sys v1.0.12
   Compiling miniz-sys v0.1.9
   Compiling url v1.4.0
   Compiling curl-sys v0.3.8
   Compiling libssh2-sys v0.2.5
   Compiling libgit2-sys v0.6.6
   Compiling toml v0.2.1
   Compiling flate2 v0.2.17
Build failed, waiting for other jobs to finish...
error: failed to run custom build command for `libssh2-sys v0.2.5`
process didn't exit successfully: `E:\Development\cargo-authors\target\debug\build\libssh2-sys-04373e2a6b69259d\build-script-build` (exit code: 101)
--- stdout
running: "cmake" "C:\\Users\\***\\.cargo\\registry\\src\\github.com-1ecc6299db9ec823\\libssh2-sys-0.2.5\\libssh2" "-G" "MSYS Makefiles" "-DCRYPTO_BACKEND=WinCNG" "-DZLIB_INCLUDE_DIR=E:\\Development\\cargo-authors\\target\\debug\\build\\libz-sys-c29f5c61ff9da9c5\\out/include" "-DBUILD_SHARED_LIBS=OFF" "-DENABLE_ZLIB_COMPRESSION=ON" "-DCMAKE_INSTALL_LIBDIR=lib" "-DBUILD_EXAMPLES=OFF" "-DBUILD_TESTING=OFF" "-DCMAKE_INSTALL_PREFIX=E:\\Development\\cargo-authors\\target\\debug\\build\\libssh2-sys-9b7d67f8c921632b\\out" "-DCMAKE_C_FLAGS= -ffunction-sections -fdata-sections -m64" "-DCMAKE_CXX_FLAGS= -ffunction-sections -fdata-sections -m64" "-DCMAKE_BUILD_TYPE=Debug"
-- The C compiler identification is GNU 6.3.0
-- Check for working C compiler: C:/msys64/usr/bin/gcc.exe
-- Check for working C compiler: C:/msys64/usr/bin/gcc.exe -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Looking for include files windows.h, bcrypt.h
-- Looking for include files windows.h, bcrypt.h - found
-- Looking for include file ntdef.h
-- Looking for include file ntdef.h - found
-- Looking for include file ntstatus.h
-- Looking for include file ntstatus.h - found
-- Looking for include files windows.h, wincrypt.h
-- Looking for include files windows.h, wincrypt.h - found
-- Configuring incomplete, errors occurred!
See also "E:/Development/cargo-authors/target/debug/build/libssh2-sys-9b7d67f8c921632b/out/build/CMakeFiles/CMakeOutput.log".

--- stderr
fatal: Not a git repository (or any of the parent directories): .git
CMake Error at C:/Program Files/CMake/share/cmake-3.7/Modules/FindPackageHandleStandardArgs.cmake:138 (message):
  Could NOT find ZLIB (missing: ZLIB_LIBRARY) (found version "1.2.8")
Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.7/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  C:/Program Files/CMake/share/cmake-3.7/Modules/FindZLIB.cmake:114 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  src/CMakeLists.txt:239 (find_package)


thread 'main' panicked at '
command did not execute successfully, got: exit code: 1

build script failed, must exit now', C:\Users\***\.cargo\registry\src\github.com-1ecc6299db9ec823\cmake-0.1.20\src\lib.rs:573
note: Run with `RUST_BACKTRACE=1` for a backtrace.

**Comment by alexcrichton** [comment]
Ah then I'm not sure :(

**Comment by Henning-K** [comment]
It seems like [this find_package](https://github.com/alexcrichton/libssh2/blob/master/src/CMakeLists.txt#L239) somehow does not find the package that is supposed to be(?) there.

Although I don't really have a clue about that file since I'm not familiar with CMake.

**Comment by alexcrichton** [comment]
Just to confirm, but do you have pkg-config installed? If so maybe cmake needs an update? (I'm just shooting in the dark here)

**Comment by Henning-K** [comment]
I have pkg-config installed from MSYS but cmake is installed on Windows at version 3.7.2 (which apparently is the latest version).

**Comment by alexcrichton** [comment]
Sorry I'm running out of ideas :(

**Comment by Henning-K** [comment]
If there's nothing more you can think of as a solution I'm probably gonna switch to the msvc toolchain and have a note on the crates.io page/ the repo site to advise windows users the build only works reliably with msvc.

+----------------------------------------------------------------------------------------------------------------+

Preface: The following is not meant to insult you or any member of the Rust community but is more of a case of me venting in general.

This kind of issue is essentially my problem with development on Windows.
Use the MSVC toolchain and everything works almost out of the box at the price of having to use the Visual Studio tooling and not everyone uses them especially as msvc is not the default on windows (rustup commands always have to be altered to use <relbranch>-msvc instead of <relbranch>).

As soon as you use the gnu toolchain and you get to something slightly complicated or involving multiple languages there' some issue...


Considering that the program I'm writing is supposed to be working on all the major platforms it's kind of a huge roadblock that the *default* toolchain on Windows isn't able to build reliably.
This probably wouldn't be a problem if I'd distribute an already compiled binary but "crates.io" / "cargo install" builds from source on installation...

**Comment by alexcrichton** [comment]
Yeah unfortunately MinGW/MSYS are sometimes a real PITA, but if MSVC works that's good!
