### ISSUE TITLE
ssh2::sftp::FileType

### ISSUE THREAD

**Issue by beamspease** [alexcrichton/ssh2-rs#63]
This should be an easy one. :)

Even though FileType is mentioned in the documentation, the module it's contained in (sftp) is private:
http://alexcrichton.com/ssh2-rs/ssh2/struct.FileStat.html#method.file_type

There are already pub methods with documentation on it.
https://github.com/alexcrichton/ssh2-rs/blob/master/src/sftp.rs#L564

**Comment by alexcrichton** [comment]
Oops, good catch!
