### ISSUE TITLE
Support keyboard-interactive authentication

### ISSUE THREAD

**Issue by griff** [alexcrichton/ssh2-rs#65]
Right now only password authentication is supported by this crate and not keyboard-interactive.

After looking around it looks like libssh2 does support it but the function libssh2_userauth_keyboard_interactive_ex is missing from from libssh2-sys.

**Comment by alexcrichton** [comment]
Ah oops didn't mean to leave it out! A PR would be most welcome to implement this!

**Comment by wez** [comment]
I have a WIP for this; it's a little more involved that it seems at first glance

**Comment by wez** [comment]
This was merged as https://github.com/alexcrichton/ssh2-rs/commit/f29ca5b717858d365f0477d824d2069ce727a702
