### ISSUE TITLE
How to use interactive shell?

### ISSUE THREAD

**Issue by vityafx** [alexcrichton/ssh2-rs#68]
How can I perform few commands in one shell?

For example, how to run `sudo`, write password to it, gain privileges, and do something after with privileges?

I have tried:

```rust
    channel.exec("sudo -s");
    println!("Writing password");
    channel.write_all(b"q\n").unwrap();
    println!("executing whoami");
    channel.exec("whoami");
    println!("whoami executed, reading");
    channel.read_to_string(&mut stdin).unwrap();
    println!("WHOAMI: {}", stdin);
```

But that does not work, it hangs on reading. Don't tell me how to avoid calling `sudo` or anything else please, I need exactly this workflow to implement.

P.S. It seems for me that each `exec` call does not take into account previous calls so `whoami` will not be executed as root but as regular user.

**Comment by alexcrichton** [comment]
Ah I actually haven't used the libssh2 apis a huge amount so I'm not so sure myself :(. Would be a good question for upstream though!
