### ISSUE TITLE
Segmentation fault - macOS

### ISSUE THREAD

**Issue by MrSpock** [alexcrichton/ssh2-rs#69]
Hi,
I'm trying to use this crate on macOS and I'm getting Segmentation fault:
Here is simple code:
```
extern crate ssh2;
use std::net::TcpStream;
use ssh2::Session;
use std::io::Read;
use std::io::Write;

fn main() {
    let tcp = TcpStream::connect("10.1.1.1:22").unwrap();
    let mut sess = Session::new().unwrap();
    sess.handshake(&tcp).unwrap();
}
```

And result:

```
   Finished dev [unoptimized + debuginfo] target(s) in 8.0 secs
Segmentation fault: 11
spock@macspock:~/telnet-client>
```

Line that is source of this is sess.handshake. Removeing this one and there is no segfault.
Wireshark shows TCP Connection is established..

**Comment by alexcrichton** [comment]
Thanks for the report! I wonder if this is https://github.com/alexcrichton/ssh2-rs/issues/54 where it's a problem with homebrew and locally installed libraries?

**Comment by MrSpock** [comment]
brew uninstall libssh2 helped and now I have another problem :)
On my Cisco router executing this:
```
   match channel.exec("show version") {
    //match channel.shell() {
        Ok(_) => {
            let _ = channel.wait_close();
        },
        Err(e) => println!("Error: {:?}", e.to_string())

    }
```
Result in this:

`Error: "[-43] Failed waiting for channel success"`

Off topic question - how you can use shell() method ?

**Comment by alexcrichton** [comment]
Ah unfortunately I'm not too privvy to the internals of libssh2 and usage, I just wrote the bindings! That may be an issue/question for upstream perhaps.

**Comment by alexcrichton** [comment]
I believe this was historically diagnosed to OpenSSL issues which should since have been fixed, so closing.
