### ISSUE TITLE
Add wrapper for libssh2_sftp_fstatvfs

### ISSUE THREAD

**Issue by durka** [alexcrichton/ssh2-rs#70]
I was looking into how to check free space via sftp, and it seems the solution is [an SSH extension](https://stackoverflow.com/questions/19769776/sftp-check-free-space-available). Is it feasible to support this, and is this the right place or would it be lower level in libssh2-sys?

**Comment by durka** [comment]
Hmm, I see that libssh2 already support libssh2_sftp_fstatvfs (but not libssh2_sftp_statvfs). Do you know why that is?

**Comment by alexcrichton** [comment]
Unsure! This may be a report for upstream libssh2 perhaps?
