### ISSUE TITLE
Is it possible to use ssh2 to connect through a bastion?

### ISSUE THREAD

**Issue by drusellers** [alexcrichton/ssh2-rs#84]
I'm happy to write up the example code once I "know" how. I was able to successfully connect to the bastion server using your examples. Now I'm trying to noodle how I would connect to the next server in the chain. Assuming that is even possible.

**Comment by alexcrichton** [comment]
I think you'd probably do this via port forwarding, right? You'd bind a local port which then tunnels through the connected server to another remote's port 22?

I thin you could also look into executing ssh and using stdin/stdout on the bastio nas well

**Comment by drusellers** [comment]
Is it possible to do "agent forwarding" with this library? The command line I was trying to model after looked like:

```
ssh -o ProxyCommand='ssh -i <key file> -W <target ip>:22 ubuntu@<bastion>' -i <key file> ubuntu@<target ip>
```
I couldn't get that to work with Rust's `Command` codes - see: https://www.reddit.com/r/rust/comments/8e96nt/hey_rustaceans_got_an_easy_question_ask_here/dy38yau/ - so I thought i'd try this library instead. Hmmm. 🤔

**Comment by alexcrichton** [comment]
Nah unfortunately I don't know enough about ssh-agent forwarding to know whether it's possible. I'd naively suspect it's possible with libssh2 but it'd require research to learn how the current ssh-agent-forwarding works and what it's forwarded over I think

**Comment by drusellers** [comment]
Right on. Thank you for your time. :) I'll dink around and see what I can make happen.
