### ISSUE TITLE
Don't use system libssh2 by default

### ISSUE THREAD

**Issue by Timmmm** [alexcrichton/ssh2-rs#87]
I had to uninstall libssh2 (see [here](https://github.com/alexcrichton/git2-rs/issues/205#issuecomment-397357835)), and looking through the `build.rs`'s I found that the `git2-rs` `build.rs` [checks for an environment variable](https://github.com/alexcrichton/git2-rs/blob/master/libgit2-sys/build.rs#L34) (which I don't set) before using `pkg-config`:

```
    if env::var("LIBGIT2_SYS_USE_PKG_CONFIG").is_ok() {
        if pkg_config::find_library("libgit2").is_ok() {
            return
        }
    }
```

But `ssh2-rs` [does not](https://github.com/alexcrichton/ssh2-rs/blob/master/libssh2-sys/build.rs#L21).

I suggest `ssh2-rs` copies the behaviour of `git2-rs` which seems a lot more sensible.

**Comment by alexcrichton** [comment]
Is there a problem using the system's libssh2? The reason for libgit2 is not applicable to libssh2, which is that libgit2's abi is quite unstable and git2-rs often depends on unreleased versions of libgit2. This crate, however, has libssh2 with a stable api and only depends on released versions

**Comment by alexcrichton** [comment]
I believe this has been implemented now
