### ISSUE TITLE
Provide an object that impls io::Read for stderr for a channel

### ISSUE THREAD

**Issue by hugoduncan** [alexcrichton/ssh2-rs#9]
To make it easier to process stderr, eg. using `read_to_string`, consider providing an instance of some type that can implement the `io::Read` trait for the stderr stream (and possibly other streams) from a channel.

**Comment by alexcrichton** [comment]
good idea!

**Comment by hugoduncan** [comment]
Thanks for the quick implementation!  I got something working, but your version was more extensive :)
