### ISSUE TITLE
Session::new() returns an option, but a result could be more appropriate

### ISSUE THREAD

**Issue by Trolldemorted** [alexcrichton/ssh2-rs#96]
While using ssh2 I was wondering why `Session::new()` returns an `Option` so I checked your documentation but it did not cover why it would ever return `None`.

Since sourcecode is the better documentation anyway I checked that:
```rust
pub fn new() -> Option<Session> {
    ::init();
    unsafe {
        let ret = raw::libssh2_session_init_ex(None, None, None,
                                               0 as *mut _);
        if ret.is_null() {None} else {Some(Binding::from_raw(ret))}
    }
}
```

I noticed that apparently libssh2 may return null, and indeed the libssh2 api states that `libssh2_session_init_ex` returns:
>Pointer to a newly allocated LIBSSH2_SESSION instance, or NULL on errors. 

What do you think of returning a result? This would allow consumers of this crate to use the try macro/question mark operator once they implement `From<ssh2::Error>` for their error type.

**Comment by alexcrichton** [comment]
Sounds reasonable to me!

**Comment by wez** [comment]
This is fixed in master and will be part of the next `ssh2` release.
