### ISSUE TITLE
Updating rust-openssl

### ISSUE THREAD

**Issue by glennpierce** [alexcrichton/ssh2-rs#98]
So I have the following dependencies

```
── ssh2 v0.3.3
│   ├── bitflags v0.7.0
│   ├── libc v0.2.45 (*)
│   └── libssh2-sys v0.2.11
│       ├── libc v0.2.45 (*)
│       ├── libz-sys v1.0.25
│       │   └── libc v0.2.45 (*)
│       │   [build-dependencies]
│       │   ├── cc v1.0.26 (*)
│       │   └── pkg-config v0.3.14 (*)
│       └── openssl-sys v0.9.40 (*)
│       [build-dependencies]
│       ├── cc v1.0.26 (*)
│       └── pkg-config v0.3.14 (*)
```

The trouble is openssl-sys v0.9.40 no longer seems supported. I can't seem to get it to compile on Fedora 29 at least. 

Is it possible to update or has the api changed ?

**Comment by alexcrichton** [comment]
Hm are you sure that openssl-sys isn't supported? That's the latest version...

**Comment by glennpierce** [comment]
Well I may be wrong . I got that info from a comment on the issues of another crate with the same problem.

"The problem is my openssl version is 1.1.1
it is not supported by
0.9.x of openssl crate :
https://github.com/sfackler/rust-openssl/blob/0.9.x/openssl/build.rs#L16
the problem is fixed in newer version of openssl crate :
https://github.com/sfackler/rust-openssl/blob/master/openssl/build.rs#L33
"

But you are right the latest release does seem to be Release v0.9.40.
Unfortunate that there is a stable crate that many others rely on that seems to be very hard to build out of the box on new Linux releases. 

I guess my best option is to try and downgrade or install a different openssl on my os.
Thanks

**Comment by alexcrichton** [comment]
Ah no worries! The problem is the `openssl` crate vs the `openssl-sys` crate. The latter supports OpenSSL 1.1.1, but the former doesn't (in the 0.9.x series). Note that the [`openssl` crate](https://crates.io/crates/openssl) is on 0.10.x now
