### ISSUE TITLE
Path delimiters are incorrect on Windows

### ISSUE THREAD

**Issue by cygnus9** [alexcrichton/ssh2-rs#99]
```std::path::PathBuf``` uses ```\``` as path delimiter on Windows when a path is constructed using ```PathBuf::push``` and thus ```Path::join```. This means that the paths created in ```sftp::readdir()``` will contain at least one ```\``` unless an empty ```dirname``` was passed.

However, those paths aren't usable when trying to open or delete a file because the sftp spec says that path delimiters must be a ```/```.

My initial thought was that ```util::path2bytes``` could fix this, but I think its signature would need to be changed because we'd suddenly need to return a temporary instead of some bytes referencing the input.

I'd be happy to make a PR, but I'm not sure what the best approach would be.

**Comment by alexcrichton** [comment]
Yeah I think it's reasonable to switch to `\` on Windows, IIRC the `tar` crate does something similar, and `path2bytes` sounds like a reasonable spot for this!
